Repository JuliaDocs/Documenter.jl, pull requests merged in 2018-09, with the labels that each got.

#816 Remove julia and osname kwarg from deploydocs
  .travis.yml
  docs/make.jl
  docs/src/man/hosting.md
  src/Documenter.jl
Labels: Type: Decision, Type: Enhancement

#825 Update DocumenterTools docs
  docs/Manifest.toml
  docs/make.jl
  docs/src/lib/internals/documentertools.md
  docs/src/lib/internals/generator.md
  docs/src/lib/public.md
  test/formats/latex.jl
Labels: Type: Documentation

#829 Slightly tweak recommended travis setup.
  .travis.yml
  docs/src/man/hosting.md
Labels: Type: Documentation

#826 Change default output format to HTML
  docs/make.jl
  docs/src/contributing.md
  docs/src/man/guide.md
  docs/src/man/hosting.md
  docs/src/man/latex.md
  docs/src/man/other-formats.md
  src/Documenter.jl
  src/Documents.jl
  src/Writers/HTMLWriter.jl
  src/Writers/LaTeXWriter.jl
  test/doctests/doctests.jl
  test/errors/make.jl
  test/examples/make.jl
  test/examples/tests.jl
  test/formats/latex.jl
  test/formats/markdown.jl
  test/missingdocs/make.jl
  test/nongit/docs/make.jl
Labels: Type: Breaking, Type: Decision, Type: Enhancement

#835 Travis.genkeys now takes a Module
  docs/src/man/hosting.md
Labels: Type: Documentation

#837 Clarify some of the debug info
  src/Documenter.jl
Labels: Type: Enhancement

#833 Deprecate Markdown/LaTeX writers as built-ins
  docs/src/man/other-formats.md
  src/Writers/Writers.jl
Labels: Type: Decision

#838 Add a more detailed walkthrough for SSH deploy-keys
  docs/make.jl
  docs/src/man/hosting.md
  docs/src/man/hosting/github-add-deploy-key.png
  docs/src/man/hosting/puttygen-export-private-key.png
  docs/src/man/hosting/puttygen-generated.png
  docs/src/man/hosting/puttygen.png
  docs/src/man/hosting_step_through.md
Labels: Type: Documentation

#840 Replace puttygen-export-private-key.png with bigger image.
  docs/src/man/hosting/puttygen-export-private-key.png
Labels: Type: Documentation

#841 Add top/bottom margin to admonitions
  assets/html/documenter.css
Labels: Type: Enhancement

#844 Recommend develop instead of add.
  .travis.yml
  docs/src/man/hosting.md
Labels: Type: Enhancement

#843 Replace DocChecks.nameof with Base.nameof
  src/DocChecks.jl
Labels: Type: Maintenance

#842 Various documentation updates
  CHANGELOG.md
  README.md
  docs/make.jl
  docs/src/index.md
  docs/src/man/doctests.md
  docs/src/man/examples.md
  docs/src/man/guide.md
  docs/src/man/hosting.md
  docs/src/man/hosting/travis-variables.png
  docs/src/man/hosting/walkthrough.md
  docs/src/man/hosting_step_through.md
  docs/src/man/latex.md
  docs/src/man/other-formats.md
  src/Documenter.jl
Labels: Type: Documentation
