Repository JuliaDocs/Documenter.jl, pull requests merged in 2018-12, with the labels that each got.

#896 Add news for v0.21 changes
  CHANGELOG.md
Labels: Type: Documentation

#898 Misc fixes
  CHANGELOG.md
  assets/latex/documenter.sty
  docs/src/lib/internals/writers.md
  docs/src/man/examples.md
  src/Documenter.jl
  src/Documents.jl
  src/Utilities/Utilities.jl
Labels: Type: Documentation, Type: Maintenance

#885 added filter function to @autodocs
  docs/src/man/syntax.md
  src/Expanders.jl
  test/examples/make.jl
  test/examples/src/lib/autodocs.md
  test/examples/tests.jl
Labels: Type: Feature

#905 deploydocs: add a forcepush keyword argument.
  CHANGELOG.md
  src/Documenter.jl
Labels: Type: Enhancement

#904 LaTeX/PDF: Add version to title and filename.
  docs/pdf/make.jl
  src/Writers/LaTeXWriter.jl
Labels: LaTeX, Type: Enhancement

#907 Handle DOCUMENTER_KEY errors better in deploydocs
  CHANGELOG.md
  src/Documenter.jl
Labels: Type: Enhancement

#909 Minor edits to the CHANGELOG
  CHANGELOG.md
Labels: Type: Documentation

#911 Some more docs for latex output.
  docs/src/man/other-formats.md
  src/Writers/LaTeXWriter.jl
Labels: Type: Documentation

#912 Remove (almost) unused internal Formats module.
  src/CrossReferences.jl
  src/Documenter.jl
  src/Documents.jl
  src/Expanders.jl
  src/Formats.jl
  src/Writers/HTMLWriter.jl
  src/Writers/LaTeXWriter.jl
  src/Writers/MarkdownWriter.jl
  src/Writers/Writers.jl
Labels: Type: Maintenance

#913 use kwarg form of Travis.genkeys in hosting.md
  docs/src/man/hosting.md
Labels: Type: Documentation

#915 Update guide.md
  docs/src/man/guide.md
Labels: Type: Documentation

#917 Don't deploy documentation on cron jobs
  CHANGELOG.md
  src/Documenter.jl
Labels: Type: Enhancement

#919 Document env. variables affecting deploydocs
  src/Documenter.jl
Labels: Type: Documentation
