Repository JuliaDocs/Documenter.jl, pull requests merged in 2018-03, with the labels that each got.

#654 use invokelatest when calling showerror, fix #653
  src/DocChecks.jl
  test/examples/src/index.md
Labels: Type: Bug

#650 support kwargs for doctests
  docs/src/man/doctests.md
  src/DocChecks.jl
  test/errors/src/index.md
  test/examples/src/index.md
Labels: Type: Feature

#655 get rid of some 0.4 specific docs
  docs/src/man/latex.md
Labels: Type: Documentation

#657 more deprecation silencing
  REQUIRE
  src/Builder.jl
  src/DocSystem.jl
  src/Documenter.jl
  src/Expanders.jl
  src/Utilities/Utilities.jl
  src/Writers/HTMLWriter.jl
  src/Writers/LaTeXWriter.jl
  src/Writers/MarkdownWriter.jl
  test/examples/src/index.md
  test/examples/src/man/tutorial.md
  test/utilities.jl
Labels: Type: Maintenance

#664 move Travis module to its own file
  src/Documenter.jl
  src/Travis.jl
Labels: Type: Maintenance

#665 remove badges for 0.4 and 0.5
  README.md
Labels: Type: Documentation

#656 add doctest = :fix option to makedocs
  REQUIRE
  docs/src/man/doctests.md
  src/DocChecks.jl
  src/Documents.jl
  test/doctests/broken.jl
  test/doctests/broken.md
  test/doctests/doctests.jl
  test/doctests/fixed.jl
  test/doctests/fixed.md
  test/runtests.jl
Labels: Type: Feature

#672 don't be so picky about number of spaces in `# hide`
  src/Expanders.jl
  test/examples/src/lib/functions.md
Labels: Type: Enhancement

#670 doctest = :fix with filters
  docs/src/man/doctests.md
  src/DocChecks.jl
  test/doctests/broken.jl
  test/doctests/broken.md
  test/doctests/fixed.jl
  test/doctests/fixed.md
Labels: Type: Bug, Type: Maintenance

#671 print line number range for failed doctests
  src/DocChecks.jl
  test/doctests/doctests.jl
Labels: Type: Enhancement

#677 contains(haystack, needle) -> occursin(needle, haystack)
  REQUIRE
  src/CrossReferences.jl
  src/Deps.jl
  src/DocChecks.jl
  src/Documenter.jl
  src/Expanders.jl
  src/Utilities/DOM.jl
  src/Utilities/Utilities.jl
  src/Writers/HTMLWriter.jl
  src/Writers/LaTeXWriter.jl
  test/utilities.jl
Labels: Type: Maintenance

#684 Mind indentation when looking for source code
  src/DocChecks.jl
  test/doctests/broken.jl
  test/doctests/broken.md
  test/doctests/fixed.jl
  test/doctests/fixed.md
Labels: Type: Bug, Type: Maintenance

#690 fix #689
  src/Utilities/Utilities.jl
Labels: Type: Bug

#691 use with_logger when evaluating output
  src/Utilities/Utilities.jl
  test/utilities.jl
Labels: Type: Bug
