Repository JuliaDocs/Documenter.jl, pull requests merged in 2018-10, with the labels that each got.

#847 Correct selector -> version in changelog.
  CHANGELOG.md
Labels: Type: Documentation

#848 set IO context for doctest output relative to sandbox module
  src/DocTests.jl
Labels: Type: Maintenance

#849 Backports for 0.19.7
  src/DocChecks.jl
Labels: Type: Backport

#852 Fix Utilities.submodules for module aliases
  src/Utilities/Utilities.jl
  test/utilities.jl
Labels: Type: Bug

#792 Make the navigation bar automatically scroll to the selected item
  assets/html/documenter.css
  assets/html/documenter.js
Labels: Type: Enhancement

#856 Update doc section on version deployment.
  docs/src/man/hosting.md
Labels: Type: Documentation

#862 Fixes #855
  assets/html/documenter.css
Labels: Type: Bug

#859 Backports for 0.19.7 (2)
  src/Utilities/Utilities.jl
  test/utilities.jl
Labels: Type: Backport

#865 Move non-package examples to their own section
  CHANGELOG.md
  docs/src/man/examples.md
Labels: Type: Documentation

#867 Current package as a dep in docs/Project.toml
  docs/src/man/hosting.md
Labels: Type: Documentation

#870 Update makedocs(format=) docstring
  src/Documenter.jl
Labels: Type: Documentation

#871 Miscellaneous updates
  .appveyor.yml
  .gitignore
  .travis.yml
  docs/Manifest.toml
  docs/Project.toml
  src/Documenter.jl
Labels: Type: Documentation, Type: Maintenance
