Repository JuliaDocs/Documenter.jl, pull requests merged in 2018-02, with the labels that each got.

#643 Deprecation fixes
  REQUIRE
  src/CrossReferences.jl
  src/DocChecks.jl
  src/DocSystem.jl
  src/Documenter.jl
  src/Documents.jl
  src/Expanders.jl
  src/Utilities/MDFlatten.jl
  src/Utilities/TextDiff.jl
  src/Utilities/Utilities.jl
  src/Walkers.jl
  src/Writers/HTMLWriter.jl
  src/Writers/LaTeXWriter.jl
  src/Writers/MarkdownWriter.jl
  test/docsystem.jl
  test/formats/markdown.jl
  test/mdflatten.jl
Labels: Type: Bug, Type: Maintenance

#641 Don't use std(in|out|err) as identifiers
  src/Utilities/Utilities.jl
Labels: Type: Bug

#644 Escape all characters not allowed in JS strings
  src/Writers/HTMLWriter.jl
  test/htmlwriter.jl
  test/runtests.jl
Labels: Type: Bug

#642 Updated URL
  docs/src/index.md
Labels: Type: Documentation

#637 Make menu section separation darker
  assets/html/documenter.css
Labels: Type: Enhancement

#646 Some more deprecation fixes
  src/DocChecks.jl
  src/Documenter.jl
  src/Selectors.jl
Labels: Type: Maintenance

#647 Bring back color printing
  src/DocChecks.jl
  src/Expanders.jl
  src/Utilities/DOM.jl
  src/Utilities/MDFlatten.jl
  src/Utilities/Utilities.jl
  src/Writers/HTMLWriter.jl
Labels: Type: Maintenance

#640 HTMLWriter.jl: lowercase categories
  src/Writers/HTMLWriter.jl
Labels: Type: Enhancement

#648 A few doc updates
  README.md
  docs/make.jl
  docs/src/man/contributing.md
  docs/src/man/examples.md
  docs/src/man/internals.md
  docs/src/man/syntax.md
  src/Generator.jl
  test/formats/latex.jl
Labels: Type: Documentation

#649 STDOUT -> stdout and STDERR -> stderr
  REQUIRE
  docs/src/man/syntax.md
  src/DocChecks.jl
  src/Expanders.jl
  src/Utilities/Utilities.jl
  test/examples/src/man/tutorial.md
Labels: Type: Maintenance
