Repository JuliaDocs/Documenter.jl, pull requests merged in 2018-07, with the labels that each got.

#753 Adds FourierFlows.jl in Registered packages list
  docs/src/man/examples.md
Labels: Type: Documentation

#755 fix errors from printing nothing
  src/DocSystem.jl
  src/Utilities/Utilities.jl
Labels: Type: Maintenance

#759 Add inline WebP/GIF/JPEG images
  src/Expanders.jl
  test/examples/images/logo.gif
  test/examples/images/logo.jpg
  test/examples/images/logo.png
  test/examples/images/logo.webp
  test/examples/src/man/tutorial.md
Labels: Type: Enhancement

#754 Play with search's editDistance
  assets/html/search.js
Labels: Type: Enhancement

#762 Remove AppVeyor allowed failures
  appveyor.yml
Labels: Type: Maintenance

#763 fix pdf generation in prescence of hidden pages
  src/Writers/LaTeXWriter.jl
  test/formats/latex.jl
Labels: Type: Bug

#769 Allow HTTP/2 in link-checks
  src/DocChecks.jl
Labels: Type: Bug
