Repository JuliaDocs/Documenter.jl, pull requests merged in 2018-04, with the labels that each got.

#698 add Gadfly.jl to examples
  docs/src/man/examples.md
Labels: Type: Documentation

#699 Add support for `repo_root()` to function inside of git worktrees
  src/Utilities/Utilities.jl
Labels: Type: Bug

#695 add continued = (false|true) kwarg to at-example
  docs/src/man/syntax.md
  src/Expanders.jl
  test/examples/src/lib/functions.md
Labels: Type: Feature

#700 Add EditURL key to at-meta block
  docs/src/man/syntax.md
  src/Writers/HTMLWriter.jl
Labels: Type: Feature

#702 Allow Markdown in page title overrides
  src/Writers/HTMLWriter.jl
  test/examples/make.jl
Labels: Type: Enhancement

#708 only deploy to stable if we build the latest tag
  src/Documenter.jl
Labels: Type: Bug

#711 rethrow InterruptException, fix #687
  src/Utilities/Utilities.jl
Labels: Type: Enhancement

#712 Make julia a required kwarg in deploydocs
  docs/make.jl
  src/Documenter.jl
  test/errors/deploydocs.jl
  test/runtests.jl
Labels: Type: Enhancement

#714 Update deploydocs on Hosting page
  docs/src/lib/internals/documenter.md
  docs/src/man/hosting.md
  src/Documenter.jl
Labels: Type: Documentation

#715 Remove Travis workaround
  .travis.yml
Labels: Type: Maintenance

#717 Handle non-repo builds
  .gitignore
  src/Utilities/Utilities.jl
  test/nongit/docs/make.jl
  test/nongit/docs/src/index.md
  test/nongit/tests.jl
  test/runtests.jl
  test/utilities.jl
Labels: Type: Bug
