Repository JuliaDocs/Documenter.jl, pull requests merged in 2018-11, with the labels that each got.

#877 Typo in Documenter / HTMLWriter.jl
  src/Writers/HTMLWriter.jl
Labels: Type: Documentation

#878 Fix logic in should_deploy.
  src/Documenter.jl
Labels: Type: Bug

#882 Add NLOptControl.jl to examples
  docs/src/man/examples.md
Labels: Type: Documentation

#879 Add support for FTP in linkcheck, disable other protocols
  src/DocChecks.jl
  test/docchecks.jl
  test/runtests.jl
Labels: Status: Needs News, Type: Enhancement

#864 Allow arbitrary variables to be passed to be stored in User and Internal
  docs/make.jl
  src/Documenter.jl
  src/Documents.jl
  src/Writers/HTMLWriter.jl
  test/examples/make.jl
Labels: Status: Needs News, Type: Enhancement, Type: Feature

#869 Document how to disable html_prettyurls for local builds
  docs/src/man/guide.md
  src/Writers/HTMLWriter.jl
Labels: Type: Documentation

#887 Add a note on Pkg.build for packages with build scripts.
  docs/src/man/hosting.md
Labels: Type: Documentation

#888 Replace deprecated `doc"""` syntax
  docs/src/man/latex.md
Labels: Type: Documentation
