Repository JuliaDocs/Documenter.jl, pull requests merged in 2018-08, with the labels that each got.

#773 AppVeyor / Travis updates
  .travis.yml
  appveyor.yml
Labels: Type: Maintenance

#777 A few deprecation fixes
  REQUIRE
  docs/src/man/examples.md
  docs/src/man/guide.md
  docs/src/man/hosting.md
  src/DocChecks.jl
  src/Documenter.jl
  src/Travis.jl
  test/generate.jl
  test/nongit/tests.jl
Labels: Type: Maintenance

#786 Add 1.0 CI targets and get the tests to pass again
  .travis.yml
  appveyor.yml
  test/examples/src/lib/functions.md
  test/examples/src/man/tutorial.md
Labels: Type: Maintenance

#782 Bump lunr.js to v2.3.1
  assets/html/search.js
Labels: Type: Bug

#788 Fix doctest = :fix with empty output, fix #772.
  src/DocChecks.jl
  test/doctests/broken.jl
  test/doctests/broken.md
  test/doctests/fixed.jl
  test/doctests/fixed.md
Labels: Type: Bug

#775 Move Selectors and doctesting code
  docs/make.jl
  docs/src/lib/internals/doctests.md
  src/Builder.jl
  src/DocChecks.jl
  src/DocTests.jl
  src/Documenter.jl
  src/Expanders.jl
  src/Utilities/Selectors.jl
  src/Utilities/Utilities.jl
  src/Writers/Writers.jl
Labels: Type: Maintenance

#764 Support inline html output
  src/Expanders.jl
  test/examples/src/man/tutorial.md
Labels: Type: Enhancement

#791 Make sure we have LF line endings only.
  src/Utilities/Utilities.jl
  test/utilities.jl
Labels: Status: Backport Needed, Type: Bug

#795 Bump Julia require to 0.7, stop testing on 0.6.
  .travis.yml
  README.md
  REQUIRE
  appveyor.yml
  docs/src/man/syntax.md
  src/Anchors.jl
  src/Builder.jl
  src/CrossReferences.jl
  src/Deps.jl
  src/DocChecks.jl
  src/DocSystem.jl
  src/DocTests.jl
  src/Documenter.jl
  src/Documents.jl
  src/Expanders.jl
  src/Formats.jl
  src/Generator.jl
  src/Travis.jl
  src/Utilities/DOM.jl
  src/Utilities/MDFlatten.jl
  src/Utilities/Selectors.jl
  src/Utilities/TextDiff.jl
  src/Utilities/Utilities.jl
  src/Writers/HTMLWriter.jl
  src/Writers/LaTeXWriter.jl
  src/Writers/MarkdownWriter.jl
  src/Writers/Writers.jl
  test/docsystem.jl
  test/doctests/doctests.jl
  test/dom.jl
  test/examples/make.jl
  test/examples/src/lib/functions.md
  test/examples/src/man/tutorial.md
  test/examples/tests.jl
  test/formats/latex.jl
  test/formats/markdown.jl
  test/generate.jl
  test/htmlwriter.jl
  test/mdflatten.jl
  test/navnode.jl
  test/nongit/tests.jl
  test/runtests.jl
  test/utilities.jl
Labels: Type: Maintenance

#794 Define include in sandbox-modules, fix #793.
  src/DocTests.jl
  src/Expanders.jl
  test/examples/src/index.md
Labels: Type: Bug, Type: Enhancement

#787 Better error message for failing to evaluate setup code, fix #785.
  src/DocTests.jl
Labels: Type: Enhancement

#798 Add --max-time 10 to curl call
  src/DocChecks.jl
Labels: Status: Backport Needed, Type: Bug

#789 Remove Travis.genkeys and Documenter.generate
  .travis.yml
  docs/Manifest.toml
  docs/Project.toml
  docs/make.jl
  docs/src/lib/public.md
  docs/src/man/guide.md
  docs/src/man/hosting.md
  src/DocChecks.jl
  src/Documenter.jl
  src/Travis.jl
  test/generate.jl
  test/runtests.jl
Labels: Type: Decision, Type: Feature

#706 stop deploying to the release- folder
  src/Documenter.jl
  src/Writers/HTMLWriter.jl
  test/htmlwriter.jl
Labels: Type: Decision, Type: Enhancement

#797 Backports for 0.19.5
  src/DocChecks.jl
  src/Utilities/Utilities.jl
  test/utilities.jl
Labels: Type: Backport

#805 Use a build stage to build docs
  .travis.yml
  coverage/Project.toml
  coverage/coverage.jl
Labels: Type: Maintenance

#809 Backports for 0.19.6
  src/DocChecks.jl
Labels: Type: Backport

#815 Silence some warning from Documenter tests.
  src/Documenter.jl
  src/Generator.jl
  test/examples/src/index.md
  test/examples/src/lib/functions.md
  test/examples/src/man/tutorial.md
  test/examples/tests.jl
Labels: Type: Maintenance

#813 Add selector argument to deploydocs
  src/Documenter.jl
  src/Writers/HTMLWriter.jl
  test/htmlwriter.jl
Labels: Type: Enhancement

#804 Use a generic description for non-GitHub hosts
  src/Utilities/Utilities.jl
  src/Writers/HTMLWriter.jl
Labels: Type: Enhancement

#824 Filter out empty expressions in parseblock
  src/Utilities/Utilities.jl
  test/utilities.jl
Labels: Type: Enhancement
