Repository JuliaDocs/Documenter.jl, pull requests merged in 2019-09, with the labels that each got.

#1121 Add hash anchor tracking to google analytics
  src/Writers/HTMLWriter.jl
Labels: Format: HTML, Status: Needs News, Type: Enhancement

#1126 fix warning: remove bad import Documenter: asset
  src/Writers/HTMLWriter.jl
Labels: Type: Bug

#1123 Some documentation tweaks
  docs/src/man/hosting/walkthrough.md
Labels: Type: Documentation

#1138 Typo fix
  docs/src/man/hosting.md
Labels: Type: Documentation
