Repository JuliaDocs/Documenter.jl, pull requests merged in 2019-07, with the labels that each got.

#1058 Disable linkcheck tests
  docs/make.jl
  test/docchecks.jl
  test/runtests.jl
Labels: Status: Backport Needed, Type: Maintenance

#1056 Backports for 0.22.5
  CHANGELOG.md
  Project.toml
  docs/make.jl
  test/docchecks.jl
Labels: Type: Backport

#1059 Rename the test stdout files to ##.stdout
  test/doctests/doctests.jl
  test/doctests/stdouts/1.stdout
  test/doctests/stdouts/11.stdout
  test/doctests/stdouts/12.stdout
  test/doctests/stdouts/2.stdout
  test/doctests/stdouts/21.stdout
  test/doctests/stdouts/22.stdout
  test/doctests/stdouts/23.stdout
  test/doctests/stdouts/24.stdout
  test/doctests/stdouts/25.stdout
  test/doctests/stdouts/3.stdout
  test/doctests/stdouts/31.stdout
  test/doctests/stdouts/32.stdout
  test/doctests/stdouts/4.stdout
  test/doctests/stdouts/5.stdout
  test/doctests/stdouts/6.stdout
  test/doctests/stdouts/7.stdout
  test/doctests/stdouts/8.stdout
Labels: Type: Maintenance

#1060 Change latest/ to dev/ in README
  README.md
Labels: Type: Documentation

#1054 Generalize doctest() API
  CHANGELOG.md
  Project.toml
  docs/src/man/doctests.md
  docs/src/showcase.md
  src/Documenter.jl
  test/doctests/doctestapi.jl
  test/manual.jl
  test/runtests.jl
Labels: Type: Documentation, Type: Enhancement

#1061 Do not declare writers <: Plugin
  CHANGELOG.md
  src/Documenter.jl
  src/Documents.jl
  src/Writers/HTMLWriter.jl
  src/Writers/LaTeXWriter.jl
  src/Writers/MarkdownWriter.jl
  test/runtests.jl
Labels: Type: Bug

#1062 Handle invalid syntax in doctests
  CHANGELOG.md
  src/DocTests.jl
  src/Documenter.jl
  src/Utilities/Utilities.jl
  test/doctests/doctestapi.jl
  test/doctests/doctests.jl
Labels: Type: Bug

#1068 Update walkthrough.md
  docs/src/man/hosting/walkthrough.md
Labels: Type: Documentation

#1069 Allow JSON@0.21 since it is non-breaking
  Project.toml
Labels: Type: Maintenance

#1066 Use DejaVu fonts in PDF builds
  CHANGELOG.md
  assets/latex/documenter.sty
  docs/src/man/other-formats.md
  src/Writers/LaTeXWriter.jl
  test/examples/make.jl
  test/examples/src/unicode.md
  test/examples/tests.jl
Labels: Format: LaTeX, Type: Enhancement

#1071 Allow DocStringExtensions 0.8, bump version to 0.22.6
  CHANGELOG.md
  Project.toml
Labels: Type: Maintenance

#1063 Set version to 0.23.0
  CHANGELOG.md
  Project.toml
Labels: Type: Maintenance

#1077 check file exists before calling realpath on it
  CHANGELOG.md
  src/Utilities/Utilities.jl
  test/examples/make.jl
  test/examples/src/lib/editurl.md
  test/examples/tests.jl
Labels: Type: Bug

#1075 Add fallback Markdown -> Markdown2 convert methods
  CHANGELOG.md
  src/DocTests.jl
  src/Utilities/Markdown2.jl
  src/Writers/HTMLWriter.jl
  test/doctests/doctestapi.jl
  test/markdown2.jl
Labels: Type: Bug
