Repository JuliaDocs/Documenter.jl, pull requests merged in 2019-06, with the labels that each got.

#1033 Add output-checking tests for doctests
  .gitignore
  test/doctests/doctests.jl
  test/doctests/fix/broken.jl
  test/doctests/fix/broken.md
  test/doctests/fix/fixed.jl
  test/doctests/fix/fixed.md
  test/doctests/fix/tests.jl
  test/doctests/src/FooBroken.jl
  test/doctests/src/FooWorking.jl
  test/doctests/src/broken.md
  test/doctests/src/foobroken.md
  test/doctests/src/fooworking.md
  test/doctests/src/working.md
  test/doctests/stdouts/stdout.1
  test/doctests/stdouts/stdout.11
  test/doctests/stdouts/stdout.12
  test/doctests/stdouts/stdout.2
  test/doctests/stdouts/stdout.3
  test/doctests/stdouts/stdout.4
  test/doctests/stdouts/stdout.5
  test/doctests/stdouts/stdout.6
  test/doctests/stdouts/stdout.7
  test/doctests/stdouts/stdout.8
  test/runtests.jl
Labels: Type: Maintenance

#1036 Remove deprecations from test/examples/make.jl
  Project.toml
  test/examples/make.jl
Labels: Type: Maintenance

#1029 Allow build order of pages to be specified
  CHANGELOG.md
  src/Documenter.jl
  src/Documents.jl
  src/Expanders.jl
  test/examples/make.jl
  test/examples/src/expandorder/00.md
  test/examples/src/expandorder/01.md
  test/examples/src/expandorder/AA.md
  test/examples/tests.jl
Labels: Type: Enhancement, Type: Feature

#1037 Add Random as test. dependency
  Project.toml
Labels: Type: Maintenance

#1025 Add option to change working directory for evaluation of example code
  .gitignore
  CHANGELOG.md
  docs/src/man/syntax.md
  src/Builder.jl
  src/Documenter.jl
  src/Documents.jl
  src/Expanders.jl
  test/runtests.jl
  test/utilities.jl
  test/workdir/make.jl
  test/workdir/src/file.md
  test/workdir/src/index.md
  test/workdir/src/subdir/file.md
  test/workdir/src/subdir/index.md
  test/workdir/tests.jl
Labels: Type: Feature

#1034 Insert video HTML tag for images ending with ".webm"
  CHANGELOG.md
  assets/html/documenter.css
  src/Writers/HTMLWriter.jl
Labels: Format: HTML, Type: Enhancement

#1042 Update analytics ID
  docs/make.jl
Labels: Type: Documentation

#1044 Bump DocStringExtensions
  Project.toml
  docs/src/man/examples.md
Labels: Type: Documentation, Type: Maintenance

#1047 Build non-pages pages too in HTMLWriter
  CHANGELOG.md
  src/Writers/HTMLWriter.jl
  test/examples/make.jl
  test/examples/src/omitted.md
  test/examples/tests.jl
Labels: Type: Bug
