Repository JuliaDocs/Documenter.jl, pull requests merged in 2019-10, with the labels that each got.

#1141 NFC: Move reading of commit sha.
  src/Documenter.jl
Labels: Type: Maintenance

#1143 Allow failures on Julia nightly
  .appveyor.yml
  .travis.yml
Labels: Type: Maintenance

#1137 Scale figures to textwidth in latex writer
  CHANGELOG.md
  assets/latex/documenter.sty
  src/Writers/LaTeXWriter.jl
Labels: Format: LaTeX, Type: Enhancement

#1147 [NFC] Factor out Travis environment reading
  CHANGELOG.md
  docs/src/man/hosting.md
  src/Documenter.jl
  src/deployconfig.jl
  test/deployconfig.jl
  test/runtests.jl
Labels: Type: Feature, Type: Maintenance

#1144 Builtin support for GitHub Actions
  CHANGELOG.md
  docs/src/man/hosting.md
  src/deployconfig.jl
  test/deployconfig.jl
Labels: Type: Feature, Type: Maintenance

#1152 Auto detect deploy system.
  CHANGELOG.md
  src/Documenter.jl
  src/deployconfig.jl
  test/deployconfig.jl
Labels: Type: Enhancement

#1154 Fix documentation build
  docs/Project.toml
  docs/src/lib/public.md
  docs/src/man/hosting.md
Labels: Type: Documentation

#1153 Use proper sandbox for at-setup blocks too
  CHANGELOG.md
  src/Expanders.jl
  test/examples/src/index.md
Labels: Status: Backport Needed, Type: Bug

#1155 [release-0.23] Backports for 0.23.4
  CHANGELOG.md
  Project.toml
  docs/Project.toml
  src/Expanders.jl
  test/examples/src/index.md
Labels: Type: Backport

#1156 Misc doc changes related to recent code changes
  docs/src/man/hosting.md
  docs/src/man/hosting/walkthrough.md
Labels: Type: Documentation

#1161 Support for pushing with https instead of ssh
  docs/src/man/hosting.md
  docs/src/man/hosting/walkthrough.md
  src/Documenter.jl
  src/deployconfig.jl
  test/deployconfig.jl
Labels: Type: Feature

#1166 Reorganize test/examples
  .travis.yml
  CHANGELOG.md
  src/Writers/LaTeXWriter.jl
  test/TestUtilities.jl
  test/examples/make.jl
  test/examples/src.latex_simple/index.md
  test/examples/src/latex.md
  test/examples/tests.jl
  test/examples/tests_latex.jl
Labels: Format: LaTeX, Type: Bug, Type: Enhancement, Type: Maintenance

#1167 Various style fixes for new front end
  assets/html/scss/_a11y-dark.scss
  assets/html/scss/documenter-dark.scss
  assets/html/scss/documenter-light.scss
  assets/html/scss/documenter/_overrides.scss
  assets/html/scss/documenter/_patches.scss
  assets/html/scss/documenter/_theme_overrides.scss
  assets/html/scss/documenter/_variables.scss
  assets/html/scss/documenter/components/_docstring.scss
  assets/html/scss/documenter/layout/_sidebar.scss
  assets/html/scss/highlightjs/a11y-dark.css
  assets/html/scss/highlightjs/default.css
  assets/html/themes/documenter-dark.css
  assets/html/themes/documenter-light.css
  src/Writers/HTMLWriter.jl
  test/examples/make.jl
  test/examples/src/man/style.md
  test/examples/tests.jl
Labels: Format: HTML
