Repository JuliaDocs/Documenter.jl, pull requests merged in 2019-02, with the labels that each got.

#935 Wrap method name in Code in missing doc admonition
  CHANGELOG.md
  src/Expanders.jl
  src/Utilities/Utilities.jl
  test/utilities.jl
Labels: Type: Enhancement

#934 Make linkcheck work on servers without HEAD, and add FTP status checking
  src/DocChecks.jl
  test/docchecks.jl
Labels: Type: Bug

#939 Backports for 0.21.2
  CHANGELOG.md
  src/DocChecks.jl
  test/docchecks.jl
Labels: Type: Backport

#938 Fix non-text/plain output for Markdown and LaTeX
  CHANGELOG.md
  src/Documents.jl
  src/Expanders.jl
  src/Utilities/Utilities.jl
  src/Writers/HTMLWriter.jl
  src/Writers/LaTeXWriter.jl
  src/Writers/MarkdownWriter.jl
Labels: Type: Enhancement

#941 Call abspath on the argument in the sandboxes include function.
  CHANGELOG.md
  docs/src/man/syntax.md
  src/Expanders.jl
Labels: Type: Bug

#946 Bump lunr.js and lodash to latest patch release
  assets/html/search.js
Labels: Type: Bug

#948 Render text/markdown in MarkdownWriter
  src/Utilities/Utilities.jl
  src/Writers/HTMLWriter.jl
  src/Writers/LaTeXWriter.jl
  src/Writers/MarkdownWriter.jl
  test/examples/src/index.md
  test/examples/tests.jl
Labels: Status: Needs News, Type: Enhancement

#952 Add CHANGELOG entries
  CHANGELOG.md
Labels: Type: Documentation

#954 Add missing closing quotation mark.
  src/Documenter.jl
Labels: Status: Backport Needed, Type: Maintenance

#951 Backports for 0.21.3
  CHANGELOG.md
  assets/html/search.js
  src/Documenter.jl
Labels: Type: Backport

#953 Update HTMLWriter logo handling and arguments
  CHANGELOG.md
  docs/make.jl
  docs/src/assets/logo.png
  docs/src/assets/logo.svg
  src/Documenter.jl
  src/Documents.jl
  src/Writers/HTMLWriter.jl
  test/examples/make.jl
Labels: Type: Documentation, Type: Enhancement

#957 Misc cleanup
  src/DocTests.jl
Labels: Type: Maintenance

#960 fix #959: jldoctest output
  src/DocTests.jl
  src/Expanders.jl
  test/examples/src/index.md
Labels: Status: Backport Needed

#958 Use logging system for doctest-failure reporting.
  CHANGELOG.md
  src/DocTests.jl
  src/Utilities/TextDiff.jl
  src/Utilities/Utilities.jl
Labels: Type: Enhancement, Type: Maintenance

#961 Backports for 0.21.4
  CHANGELOG.md
  src/DocTests.jl
  src/Expanders.jl
  test/examples/src/index.md
Labels: Type: Backport

#967 Fix depwarn for format
  CHANGELOG.md
  src/Documenter.jl
Labels: Type: Bug

#968 Backports for 0.21.5
  CHANGELOG.md
  src/Documenter.jl
Labels: Type: Backport

#972 Reinstante limit=true for text/plain output.
  src/Utilities/Utilities.jl
Labels: Type: Bug
