Repository JuliaDocs/Documenter.jl, pull requests merged in 2019-08, with the labels that each got.

#1080 Use tree-like formatting in docs
  docs/src/man/guide.md
Labels: Type: Documentation

#1082 Fix MD2 parsing for empty headings
  CHANGELOG.md
  Project.toml
  docs/src/index.md
  src/DocTests.jl
  src/Documents.jl
  src/Utilities/Markdown2.jl
  test/examples/src/index.md
  test/markdown2.jl
Labels: Type: Bug

#1084 Fix messed up links in CHANGELOG.md
  CHANGELOG.md
Labels: Type: Documentation

#1090 Different logo for dark themes
  assets/html/scss/documenter-dark.scss
  assets/html/scss/documenter/_elements.scss
  assets/html/scss/documenter/_variables.scss
  assets/html/themes/documenter-dark.css
  assets/html/themes/documenter-light.css
  docs/src/assets/logo-dark.svg
  src/Writers/HTMLWriter.jl
Labels: Format: HTML, Type: Enhancement

#1089 Add option to hide sitename in sidebar
  src/Writers/HTMLWriter.jl
Labels: Format: HTML, Status: Needs News, Type: Enhancement

#1093 Fix checkdocs docstring
  src/Documenter.jl
Labels: Type: Documentation

#1096 Fix tests on nightly
  test/doctests/doctestapi.jl
  test/manual.jl
Labels: Type: Maintenance

#1098 Clean up the tests a bit
  test/TestUtilities.jl
  test/examples/make.jl
  test/expanders.jl
  test/htmlwriter.jl
  test/runtests.jl
Labels: Type: Maintenance

#1099 Test Julia 1.2 & PRs only
  .travis.yml
Labels: Type: Maintenance

#1092 Generate documenter.js on the fly
  assets/html/documenter.js
  assets/html/js/headroom.js
  assets/html/js/highlight.js
  assets/html/js/katex.js
  assets/html/js/settings.js
  assets/html/js/sidebar.js
  assets/html/js/themes.js
  assets/html/js/versions.js
  assets/html/search.js
  docs/make.jl
  docs/src/lib/internals/jsdependencies.md
  docs/src/lib/internals/writers.md
  src/Utilities/JSDependencies.jl
  src/Utilities/Utilities.jl
  src/Writers/HTMLWriter.jl
  test/utilities.jl
Labels: Format: HTML, Type: Maintenance

#1094 Add an option to include additional highlight.js languages
  assets/html/js/highlight.js
  docs/make.jl
  src/Writers/HTMLWriter.jl
  test/examples/make.jl
  test/examples/tests.jl
Labels: Format: HTML, Status: Needs News, Type: Enhancement

#1105 Compat caret specifier
  docs/src/man/hosting.md
Labels: Type: Documentation

#1107 Remove deprecated makedocs and deploydocs keywords
  src/Documenter.jl
  test/formats/markdown.jl
Labels: Status: Needs News, Type: Breaking

#1109 Don't cleanup temporary directories meant for the user to inspect.
  src/Writers/LaTeXWriter.jl
Labels: Type: Maintenance

#1097 Support both MathJax and KaTeX + allow configuration
  Project.toml
  assets/html/js/katex.js
  docs/src/man/hosting.md
  src/Documenter.jl
  src/Utilities/JSDependencies.jl
  src/Writers/HTMLWriter.jl
  test/TestUtilities.jl
  test/examples/make.jl
  test/examples/src/man/tutorial.md
  test/htmlwriter.jl
  test/utilities.jl
Labels: Format: HTML, Status: Needs News, Type: Enhancement

#1112 Increase search result prominence for close matches in result titles
  assets/html/search.js
Labels: Format: HTML, Status: Needs News, Type: Enhancement

#1108 User API for non-local assets
  docs/src/lib/public.md
  src/Documenter.jl
  src/Writers/HTMLWriter.jl
  test/TestUtilities.jl
  test/examples/make.jl
  test/examples/src/man/tutorial.md
  test/examples/tests.jl
  test/htmlwriter.jl
Labels: Format: HTML, Status: Needs News, Type: Enhancement

#1113 Improving search matching based on result title: Increase field boost to 100
  assets/html/search.js
Labels: Format: HTML, Status: Needs News, Type: Enhancement

#1116 Add Julia 1.3 on Travis, don't test on Julia 1.1.
  .appveyor.yml
  .travis.yml
Labels: Type: Maintenance

#1115 Fix tests when `Pkg.add`ed
  CHANGELOG.md
  test/doctests/fix/tests.jl
Labels: Status: Backport Needed

#1117 [release-0.23] Backports for 0.23.3
  .appveyor.yml
  .travis.yml
  CHANGELOG.md
  Project.toml
  test/doctests/doctestapi.jl
  test/doctests/fix/tests.jl
  test/manual.jl
Labels: Type: Backport
