Repository JuliaDocs/Documenter.jl, pull requests merged in 2019-11, with the labels that each got.

#1170 Add missing CHANGELOG entries for 0.24.0
  CHANGELOG.md
Labels: Type: Documentation

#1172 Use overflow-wrap to break words in case of overflow
  assets/html/scss/documenter/_patches.scss
  assets/html/scss/documenter/layout/_main.scss
  assets/html/themes/documenter-dark.css
  assets/html/themes/documenter-light.css
Labels: Format: HTML, Type: Enhancement

#1171 Add User and IdentitesOnly lines to the generated SSH config
  CHANGELOG.md
  src/Documenter.jl
Labels: Type: Enhancement

#1173 Deprecate edit_branch in favor of edit_link
  CHANGELOG.md
  src/Utilities/Utilities.jl
  src/Writers/HTMLWriter.jl
Labels: Format: HTML, Type: Enhancement

#1176 Add more information to warning about unresolved link
  src/Writers/HTMLWriter.jl
Labels: Type: Enhancement

#1181 add DrWatson to examples
  docs/src/man/examples.md
Labels: Type: Documentation

#1179 add comment about specific method docstrings
  docs/src/man/syntax.md
Labels: Type: Documentation

#1180 Support push preview docs.
  CHANGELOG.md
  docs/make.jl
  docs/src/man/hosting.md
  src/Documenter.jl
  src/deployconfig.jl
  test/deployconfig.jl
Labels: Type: Feature

#1183 Support SSH deploy keys from GH Actions.
  docs/src/man/hosting.md
  src/deployconfig.jl
  test/deployconfig.jl
Labels: Type: Enhancement

#1186 Post a GitHub status with a link to generated documentation.
  CHANGELOG.md
  src/Documenter.jl
  src/deployconfig.jl
Labels: Type: Enhancement

#1178 Prepare version 0.24
  Project.toml
  assets/html/scss/documenter/_elements.scss
  assets/html/scss/documenter/_patches.scss
  assets/html/scss/documenter/_variables.scss
  assets/html/scss/documenter/components/_docstring.scss
  assets/html/themes/documenter-dark.css
  assets/html/themes/documenter-light.css
  docs/DocumenterShowcase.jl
  docs/Project.toml
  docs/src/lib/internals/documentertools.md
  src/Writers/HTMLWriter.jl
  src/deployconfig.jl
  test/themes/Manifest.toml
  test/themes/Project.toml
Labels: Format: HTML

#1189 Update JS/CSS dependencies
  CHANGELOG.md
  docs/src/lib/internals/writers.md
  src/Documenter.jl
  src/Writers/HTMLWriter.jl
Labels: Format: HTML, Type: Enhancement

#1194 Fix mktempdir bug on Julia > 1.3.
  Project.toml
  src/Writers/LaTeXWriter.jl
Labels: Format: LaTeX, Type: Bug

#1197 Add CHANGELOG for 0.24.{1,2}
  CHANGELOG.md
Labels: Type: Documentation

#1199 Update CI to Julia 1.3.
  .appveyor.yml
  .travis.yml
Labels: Type: Maintenance
