Repository JuliaDocs/Documenter.jl, pull requests merged in 2019-05, with the labels that each got.

#1004 Fix Utilities.url if in a submodule
  CHANGELOG.md
  src/Utilities/Utilities.jl
  test/utilities.jl
Labels: Type: Bug

#1009 Fix spurious "Package.Package missing" warnings
  CHANGELOG.md
  src/DocChecks.jl
Labels: Type: Bug

#1006 Remove various doc issues causing build warnings
  docs/make.jl
  docs/src/contributing.md
  docs/src/man/examples.md
  src/Writers/LaTeXWriter.jl
Labels: Type: Documentation, Type: Maintenance

#1014 Fix strict=true not failing for doctest failures
  src/DocTests.jl
Labels: Type: Bug

#1010 Update Documenter Version in hosting.md
  docs/src/man/hosting.md
Labels: Type: Documentation

#1016 Set version to 0.22.4
  Project.toml
Labels: Type: Maintenance

#1017 Use an at-eval block to parse correct Documenter version at build-time.
  docs/src/man/hosting.md
Labels: Type: Documentation

#1005 Improve logo link URLs
  CHANGELOG.md
  src/Writers/HTMLWriter.jl
Labels: Type: Enhancement

#1015 Misc simplifications
  .appveyor.yml
  .travis.yml
  CHANGELOG.md
  Project.toml
  README.md
  coverage/.codecov.yml
  coverage/coverage.jl
Labels: Type: Maintenance

#1028 Fix doctest output labelling
  CHANGELOG.md
  src/DocTests.jl
Labels: Type: Enhancement
