Repository JuliaDocs/Documenter.jl, pull requests merged in 2019-03, with the labels that each got.

#971 Small changes for GitLab
  CHANGELOG.md
  src/Documenter.jl
Labels: Type: Bug, Type: Enhancement

#966 refactor HTMLWriter search index construction
  .gitignore
  .travis.yml
  CHANGELOG.md
  Project.toml
  REQUIRE
  docs/Project.toml
  docs/pdf/Manifest.toml
  src/Writers/HTMLWriter.jl
  test/htmlwriter.jl
Labels: Type: Enhancement, Type: Maintenance

#980 Highlight indented method signatures in docstrings by default
  CHANGELOG.md
  src/Documenter.jl
  src/Documents.jl
  src/Expanders.jl
  test/runtests.jl
Labels: Type: Enhancement

#984 Update doctests.md: Fixed typo
  docs/src/man/doctests.md
Labels: Type: Documentation

#985 Add a note about escaping copied LaTeX equations
  docs/src/index.md
  docs/src/man/latex.md
  docs/src/man/syntax.md
Labels: Type: Documentation

#989 Enable table column alignment in HTML
  CHANGELOG.md
  src/Writers/HTMLWriter.jl
  test/examples/src/man/tutorial.md
Labels: Type: Bug

#991 Consider CRLF when splitting code lines
  CHANGELOG.md
  src/Expanders.jl
Labels: Type: Bug

#992 Add some more logging messages.
  src/Writers/HTMLWriter.jl
  src/Writers/LaTeXWriter.jl
  src/Writers/MarkdownWriter.jl
Labels: Type: Maintenance

#987 Display stdout if nothing result in at-example
  src/Expanders.jl
Labels: Type: Bug

#994 Use invokelatest in doctests
  CHANGELOG.md
  Project.toml
  src/DocTests.jl
  test/examples/src/index.md
Labels: Type: Bug
