Repository JuliaDocs/Documenter.jl, pull requests merged in 2019-01, with the labels that each got.

#922 Add note about @meta placement while splicing docstrings
  docs/src/man/doctests.md
Labels: Type: Documentation

#925 Remove prepended html_ from deprecation warnings.
  src/Documenter.jl
Labels: Status: Backport Needed

#926 Setting ans to a expression in REPLBlocks.
  CHANGELOG.md
  src/DocTests.jl
  src/Expanders.jl
  test/examples/src/index.md
Labels: Status: Backport Needed, Type: Bug

#929 Better log messages
  CHANGELOG.md
  src/DocTests.jl
  src/Expanders.jl
  src/Utilities/Utilities.jl
Labels: Type: Enhancement

#927 Skip keyword parsing for code-block parsing.
  CHANGELOG.md
  src/Expanders.jl
Labels: Status: Backport Needed, Type: Bug

#931 add csv rendering example with at-eval
  docs/src/man/syntax.md
Labels: Type: Documentation

#933 Separate v0.21.1 fixes in CHANGELOG
  CHANGELOG.md
Labels: Type: Documentation

#932 Backports for 0.21.1
  CHANGELOG.md
  docs/src/man/guide.md
  src/DocTests.jl
  src/Documenter.jl
  src/Expanders.jl
  test/examples/src/index.md
Labels: Type: Backport

#928 Fix incomplete at-docs block
  CHANGELOG.md
  src/Documents.jl
  src/Expanders.jl
Labels: Type: Enhancement
