Repository JuliaDocs/Documenter.jl, pull requests merged in 2019-04, with the labels that each got.

#995 document sitename.
  src/Documenter.jl
Labels: Type: Documentation

#996 Fix error when source-file can not be found.
  src/Utilities/Utilities.jl
Labels: Status: Backport Needed

#997 Documenter 0.22.2
  CHANGELOG.md
  Project.toml
Labels: Type: Documentation

#999 Fix filepath in tex file on Windows.
  CHANGELOG.md
  Project.toml
  src/Writers/LaTeXWriter.jl
Labels: Format: LaTeX, Type: Bug

#1002 Handle non-existing files in find_block_in_file
  CHANGELOG.md
  src/Utilities/Utilities.jl
Labels: Type: Bug

#1007 Remove REQUIRE, add [compat] to Project.toml.
  Project.toml
  REQUIRE
Labels: Type: Maintenance
