Repository JuliaDocs/Documenter.jl, pull requests merged in 2020-11, with the labels that each got.

#1465 Update TagBot.yml
  .github/workflows/TagBot.yml
Labels: Type: Maintenance

#1461 docs: cleaning up PR previews
  docs/src/man/hosting.md
Labels: Type: Documentation

#1468 Add page title to search results
  CHANGELOG.md
  assets/html/search.js
Labels: Format: HTML, Type: Enhancement

#1471 Add support for Azure DevOps repos
  CHANGELOG.md
  src/Documenter.jl
  src/Utilities/Utilities.jl
  src/Writers/HTMLWriter.jl
  test/utilities.jl
Labels: Type: Enhancement

#1469 Add support for deploying from Buildkite.
  CHANGELOG.md
  docs/src/man/hosting.md
  src/deployconfig.jl
  test/deployconfig.jl
Labels: Status: Backport Needed, Type: Feature

#1474 List Union{...} type aliases as "Type"
  CHANGELOG.md
  src/Utilities/Utilities.jl
  test/utilities.jl
Labels: Type: Bug

#1477 Don't run additional build stages on nightly
  .travis.yml
Labels: Type: Maintenance

#1472 Stop warning for mailto: links
  CHANGELOG.md
  src/Writers/HTMLWriter.jl
Labels: Status: Backport Needed, Type: Bug

#1456 Respect user preference for color scheme
  CHANGELOG.md
  assets/html/js/themes.js
  assets/html/themeswap.js
  src/Writers/HTMLWriter.jl
Labels: Format: HTML, Type: Enhancement

#1479 Fix the tests on nightly
  test/doctests/fix/broken.jl
  test/doctests/fix/broken.md
  test/doctests/fix/fixed.jl
  test/doctests/fix/fixed.md
  test/doctests/fix/tests.jl
  test/examples/make.jl
  test/runtests.jl
  test/utilities.jl
Labels: Status: Backport Needed, Type: Maintenance

#1478 Backports for 0.25.4
  .travis.yml
  CHANGELOG.md
  Project.toml
  docs/src/man/hosting.md
  src/Documenter.jl
  src/Utilities/Utilities.jl
  src/Writers/HTMLWriter.jl
  src/deployconfig.jl
  test/deployconfig.jl
  test/doctests/fix/broken.jl
  test/doctests/fix/broken.md
  test/doctests/fix/fixed.jl
  test/doctests/fix/fixed.md
  test/doctests/fix/tests.jl
  test/examples/make.jl
  test/runtests.jl
  test/utilities.jl
Labels: Type: Backport

#1480 Fix CHANGELOG on master
  CHANGELOG.md
Labels: Type: Maintenance

#1476 Scroll overflow for long equations
  CHANGELOG.md
  assets/html/scss/documenter/_patches.scss
  assets/html/scss/documenter/layout/_main.scss
  assets/html/themes/documenter-dark.css
  assets/html/themes/documenter-light.css
  src/Writers/HTMLWriter.jl
  test/examples/make.jl
  test/examples/src/man/style.md
  test/examples/tests.jl
Labels: Format: HTML, Status: Backport Needed, Type: Bug

#1484 Backports for 0.25.5
  CHANGELOG.md
  Project.toml
  assets/html/scss/documenter/_patches.scss
  assets/html/scss/documenter/layout/_main.scss
  assets/html/themes/documenter-dark.css
  assets/html/themes/documenter-light.css
  src/Writers/HTMLWriter.jl
  test/examples/make.jl
  test/examples/src/man/style.md
  test/examples/tests.jl
Labels: Type: Backport
