Repository JuliaDocs/Documenter.jl, pull requests merged in 2020-10, with the labels that each got.

#1422 Replace Utilities.withoutput with IOCapture
  .travis.yml
  Project.toml
  src/DocTests.jl
  src/Expanders.jl
  src/Utilities/Utilities.jl
  test/TestUtilities.jl
  test/doctests/doctestapi.jl
  test/doctests/doctests.jl
  test/runtests.jl
  test/utilities.jl
Labels: Type: Maintenance

#1425 Add a showcase example for multiple uses of the same symbol.
  docs/DocumenterShowcase.jl
  docs/src/showcase.md
Labels: Type: Documentation

#1435 Correctly accept doctestfilters kwarg in Documenter.doctest
  CHANGELOG.md
  src/Documenter.jl
  test/doctests/doctestapi.jl
Labels: Type: Bug

#1442 Update links
  docs/Project.toml
  docs/src/contributing.md
  docs/src/man/examples.md
  docs/src/man/hosting.md
  src/deployconfig.jl
  test/themes/Project.toml
Labels: Type: Documentation

#1452 Empty Selector cache before running build pipeline
  CHANGELOG.md
  src/Documenter.jl
Labels: Type: Bug

#1448 Add Gitlab deployconfig.
  CHANGELOG.md
  docs/src/man/hosting.md
  src/deployconfig.jl
  test/deployconfig.jl
Labels: Type: Enhancement

#1453 Do not capture interrupts with iocapture()
  src/DocTests.jl
  src/Expanders.jl
  test/TestUtilities.jl
  test/doctests/doctestapi.jl
  test/doctests/doctests.jl
Labels: Type: Maintenance

#1439 Set version to 0.25.3
  Project.toml
Labels: Type: Maintenance

#1426 Strip out $$ as well
  CHANGELOG.md
  src/Writers/HTMLWriter.jl
  test/examples/src/man/tutorial.md
Labels: Format: HTML, Type: Enhancement

#1460 Fix codecov upload
  .travis.yml
Labels: Type: Maintenance
