Repository JuliaDocs/Documenter.jl, pull requests merged in 2020-04, with the labels that each got.

#1280 Pass non-standard admonition categories on in HTML output
  CHANGELOG.md
  src/Writers/HTMLWriter.jl
  test/examples/src/man/style.md
  test/examples/tests.jl
Labels: Format: HTML, Status: Backport Needed, Type: Enhancement

#1284 Add example admonition css to example build
  test/examples/src/assets/custom.css
  test/examples/src/man/style.md
Labels: Type: Documentation

#1287 Fix GitHub status update when repo does not end with .jl.
  src/deployconfig.jl
Labels: Status: Backport Needed

#1281 [release-0.24] Backports for 0.24.8
  CHANGELOG.md
  Project.toml
  src/Writers/HTMLWriter.jl
  src/deployconfig.jl
  test/examples/src/man/style.md
  test/examples/tests.jl
Labels: Type: Backport

#1290 docs: fix typo in hosting.md
  docs/src/man/hosting.md
Labels: Type: Documentation

#1293 Correctly prettify canonical URLs when prettyurls=true.
  CHANGELOG.md
  src/Writers/HTMLWriter.jl
Labels: Status: Backport Needed, Type: Bug

#1294 [release-0.24] Backports for 0.24.9
  CHANGELOG.md
  Project.toml
  src/Writers/HTMLWriter.jl
Labels: Type: Backport

#1292 Omit the number for the first link fragment on a page
  CHANGELOG.md
  src/Anchors.jl
  src/CrossReferences.jl
  src/Writers/HTMLWriter.jl
  src/Writers/MarkdownWriter.jl
Labels: Type: Enhancement

#1285 Add option to specify username when deploying via ssh
  CHANGELOG.md
  docs/src/lib/internals/documenter.md
  src/Documenter.jl
  test/deployconfig.jl
Labels: Type: Enhancement

#1297 add JuliaImages as one documentation example
  docs/src/man/examples.md
Labels: Type: Documentation

#1295 Add configurable timeout for linkcheck
  CHANGELOG.md
  src/DocChecks.jl
  src/Documenter.jl
  src/Documents.jl
  test/docchecks.jl
Labels: Status: Backport Needed, Type: Enhancement

#1299 PDF/LaTeX: Escape characters in admonition titles
  CHANGELOG.md
  src/Writers/LaTeXWriter.jl
  test/examples/src.latex_simple/index.md
Labels: Format: LaTeX, Status: Backport Needed, Type: Bug

#1301 Make the depwarn test dependent on --depwarn value
  test/utilities.jl
Labels: Status: Backport Needed, Type: Maintenance, Type: Tests

#1300 [release-0.24] Backports for 0.24.10
  CHANGELOG.md
  Project.toml
  src/DocChecks.jl
  src/Documenter.jl
  src/Documents.jl
  src/Writers/LaTeXWriter.jl
  test/docchecks.jl
  test/examples/src.latex_simple/index.md
  test/utilities.jl
Labels: Type: Backport

#1298 Discard build from version number when deploying
  CHANGELOG.md
  docs/src/man/hosting.md
  src/Documenter.jl
  src/deployconfig.jl
  test/deployconfig.jl
Labels: Type: Enhancement

#1304 Create a parsedoc wrapper for more helpful errors
  src/DocSystem.jl
Labels: Type: Enhancement
