Repository JuliaDocs/Documenter.jl, pull requests merged in 2020-07, with the labels that each got.

#1356 Add .gitattributes to fix language report
  .gitattributes
Labels: Type: Maintenance

#1355 If no pages specified, put index.md in front of other pages
  CHANGELOG.md
  src/Builder.jl
  test/expanders.jl
  test/pipeline.jl
  test/runtests.jl
Labels: Type: Enhancement

#1357 Add specific HTML class to example output
  CHANGELOG.md
  assets/html/scss/documenter/components/_all.scss
  assets/html/scss/documenter/components/_example.scss
  assets/html/themes/documenter-dark.css
  assets/html/themes/documenter-light.css
  src/Writers/HTMLWriter.jl
  test/examples/tests.jl
Labels: Format: HTML, Type: Enhancement

#1360 Use consistent HTML classs for stdout/err in example
  CHANGELOG.md
  src/Expanders.jl
  test/examples/make.jl
  test/examples/src/example-output.md
  test/examples/tests.jl
Labels: Type: Enhancement

#1363 Fix exception handling in test/examples/make.jl
  test/examples/make.jl
Labels: Type: Tests

#1365 Add "Powered by ..." message to footer
  CHANGELOG.md
  assets/html/scss/documenter/layout/_main.scss
  assets/html/themes/documenter-dark.css
  assets/html/themes/documenter-light.css
  src/Writers/HTMLWriter.jl
  test/examples/make.jl
  test/htmlwriter.jl
Labels: Type: Enhancement

#1349 Log `@error` for any DocCheck which triggers a failure.
  CHANGELOG.md
  src/DocChecks.jl
Labels: Type: Enhancement

#1368 `align*` clashes with `split` and `equation*`
  CHANGELOG.md
  src/Writers/LaTeXWriter.jl
Labels: Format: LaTeX, Type: Bug

#1372 Set version to 0.25.1
  Project.toml
Labels: Type: Maintenance

#1381 Fix typo: it's structure -> its structure
  docs/src/man/guide.md
Labels: Type: Documentation
