Repository JuliaDocs/Documenter.jl, pull requests merged in 2020-05, with the labels that each got.

#1307 Add support for pushing PR previews to a different branch and/or different repo
  CHANGELOG.md
  docs/src/man/hosting.md
  src/Documenter.jl
  src/deployconfig.jl
  test/deployconfig.jl
Labels: Type: Enhancement

#1311 always use pipeline in search
  CHANGELOG.md
  assets/html/search.js
Labels: Format: HTML, Status: Backport Needed, Type: Bug

#1313 [release-0.24] Backports for 0.24.11
  CHANGELOG.md
  Project.toml
  assets/html/search.js
Labels: Type: Backport

#1310 Fix a typo in a debug statement; also add missing PR links to changelog
  CHANGELOG.md
  src/Documenter.jl
Labels: Type: Bug

#1315 Fix the `deploy_folder` fallbacks and the docstring for `deploy_folder`
  CHANGELOG.md
  docs/src/man/hosting.md
  src/deployconfig.jl
  test/deployconfig.jl
Labels: Type: Bug, Type: Documentation

#1288 Add warning about TagBot permissions
  docs/src/man/hosting.md
Labels: Type: Documentation

#1308 Added more info to hosting.md
  docs/src/man/hosting.md
Labels: Type: Documentation

#1318 Fix typo
  src/deployconfig.jl
Labels: Type: Maintenance

#1316 Clarify prettyurl ENV condition in guide.md
  docs/src/man/guide.md
Labels: Type: Documentation

#1326 Document url for hosted previews
  src/Documenter.jl
Labels: Type: Documentation

#1329 Fix link to FourierFlows.jl docs
  docs/src/man/examples.md
Labels: Type: Documentation

#1328 Have custom assets be the last elements in <head>
  CHANGELOG.md
  src/Writers/HTMLWriter.jl
Labels: Format: HTML, Type: Bug
