Repository JuliaDocs/Documenter.jl, pull requests merged in 2020-06, with the labels that each got.

#1323 Remove exported/unexported ordering override
  CHANGELOG.md
  src/Expanders.jl
Labels: Type: Bug

#1331 Fix linerange for empty svec
  src/Utilities/Utilities.jl
  test/utilities.jl
Labels: Type: Bug, Type: Maintenance

#1335 Clarify that fatal error is fine
  src/Documenter.jl
Labels: Type: Maintenance

#1339 add new platform to compile only to latex
  CHANGELOG.md
  docs/src/man/other-formats.md
  src/Writers/LaTeXWriter.jl
  test/examples/make.jl
  test/examples/tests_latex.jl
Labels: Format: LaTeX, Type: Enhancement

#1348 Run linkcheck tests only on GitHub Actions
  .github/workflows/linkcheck.yml
  test/run_docchecks.jl
  test/runtests.jl
Labels: Type: Maintenance, Type: Tests

#1345 Don't warn on 302 redirects
  CHANGELOG.md
  src/DocChecks.jl
Labels: Type: Enhancement

#1353 Add COSMO.jl to examples
  docs/src/man/examples.md
Labels: Type: Documentation

#1334 Set version to 0.25.0
  Project.toml
  docs/Project.toml
  test/themes/Project.toml
Labels: Type: Maintenance
