Repository JuliaDocs/Documenter.jl, pull requests merged in 2020-01, with the labels that each got.

#1222 Change away from red inline code color
  CHANGELOG.md
  assets/html/scss/documenter-dark.scss
  assets/html/scss/documenter/_variables.scss
  assets/html/themes/documenter-light.css
Labels: Format: HTML, Type: Enhancement

#1224 Simplify/improve GitHub actions YAML setting example
  docs/src/man/hosting.md
Labels: Type: Documentation

#1223 add support for other language in HTML tag
  CHANGELOG.md
  src/Writers/HTMLWriter.jl
Labels: Format: HTML, Type: Enhancement

#1231 Discourage use of matrix: in Travis conf
  .travis.yml
  docs/src/man/hosting.md
Labels: Type: Documentation, Type: Maintenance

#1232 Support REPL softscope for Julia 1.5.
  CHANGELOG.md
  docs/src/man/doctests.md
  docs/src/man/syntax.md
  src/DocTests.jl
  src/Expanders.jl
  test/doctests/doctests.jl
  test/doctests/src/hardscope.md
  test/doctests/src/softscope.md
  test/doctests/stdouts/41.stdout
  test/doctests/stdouts/42.stdout
Labels: Type: Maintenance
