Repository JuliaDocs/Documenter.jl, pull requests merged in 2021-08, with the labels that each got.

#1659 Fix example links
  docs/src/man/examples.md
Labels: Type: Documentation

#1657 Add `index.html` generation for redirecting to `./stable` or `./dev`
  CHANGELOG.md
  src/Documenter.jl
  src/Writers/HTMLWriter.jl
  test/htmlwriter.jl
Labels: Type: Feature

#1665 Fix PR preview verification on 1.0
  CHANGELOG.md
  src/deployconfig.jl
  test/deployconfig.jl
Labels: Type: Bug

#1663 Extra tests and assertions for asset()
  src/Writers/HTMLWriter.jl
  test/htmlwriter.jl
Labels: Type: Tests, Format: HTML

#1669 Improve the deploydocs docstring
  src/Documenter.jl
Labels: Type: Documentation

#1687 Pass file and line info to downstream loggers
  CHANGELOG.md
  src/DocTests.jl
Labels: Type: Bug
