Repository JuliaDocs/Documenter.jl, pull requests merged in 2021-03, with the labels that each got.

#1540 use valid identifiers for sandbox module names
  CHANGELOG.md
  src/DocTests.jl
Labels: Type: Maintenance

#1543 Backports for 0.26.3
  CHANGELOG.md
  Project.toml
  src/DocTests.jl
Labels: Type: Backport

#1545 Update SSH deploy example
  docs/src/man/hosting.md
Labels: Type: Documentation

#1541 Illusrtate submodules in `@autodocs` example
  docs/src/man/syntax.md
Labels: Type: Documentation

#1544 Refactor sandbox module creation
  src/DocTests.jl
  src/Expanders.jl
  src/Utilities/Utilities.jl
Labels: Type: Maintenance

#1546 Update doctests.md
  docs/src/man/doctests.md
Labels: Type: Documentation

#1551 Fix highlight.js warning due to invalid "language-none"
  CHANGELOG.md
  src/Writers/HTMLWriter.jl
Labels: Format: HTML, Type: Bug

#1552 Two doc updates for PDF output
  docs/src/man/other-formats.md
Labels: Type: Documentation

#1549 Use IOCapture v0.2
  CHANGELOG.md
  Project.toml
  src/DocTests.jl
  src/Expanders.jl
  test/TestUtilities.jl
  test/doctests/doctestapi.jl
  test/doctests/doctests.jl
Labels: Type: Maintenance

#1538 put svg with xmlns in img src tag
  CHANGELOG.md
  src/Writers/HTMLWriter.jl
  test/examples/src/man/tutorial.md
Labels: Format: HTML, Type: Enhancement

#1555 Showcase automatic signature highlighting
  docs/DocumenterShowcase.jl
Labels: Type: Documentation

#1557 Handle faulty doctest keyword arguments better
  CHANGELOG.md
  src/DocTests.jl
  test/TestUtilities.jl
  test/doctests/doctestapi.jl
Labels: Type: Enhancement

#1553 Let sitename link back to document root just like the logo.
  CHANGELOG.md
  assets/html/scss/documenter/layout/_sidebar.scss
  assets/html/themes/documenter-dark.css
  assets/html/themes/documenter-light.css
  src/Writers/HTMLWriter.jl
Labels: Format: HTML, Type: Enhancement
