Repository JuliaDocs/Documenter.jl, pull requests merged in 2021-02, with the labels that each got.

#1496 Switch CI over to GitHub Actions
  .github/workflows/CI.yml
  .travis.yml
Labels: Type: Maintenance

#1511 Check for empty CI environment variables
  CHANGELOG.md
  docs/src/man/hosting.md
  src/Documenter.jl
  src/deployconfig.jl
Labels: Status: Backport Needed, Type: Bug

#1510 Fix crash in case of empty `# output`
  CHANGELOG.md
  src/DocTests.jl
  test/doctests/src/working.md
Labels: Status: Backport Needed, Type: Bug

#1519 Normalize line breaks before replacements
  test/doctests/doctests.jl
  test/doctests/fix/tests.jl
Labels: Type: Maintenance

#1512 Clarify treatment of outputs
  docs/src/man/doctests.md
  docs/src/man/syntax.md
Labels: Type: Documentation

#1520 Fix cross-platform newline handling in doctests
  .appveyor.yml
  .github/workflows/CI.yml
  CHANGELOG.md
  test/doctests/doctests.jl
  test/doctests/fix/tests.jl
Labels: Status: Backport Needed, Type: Bug, Type: Maintenance

#1518 Fix multiline display equations in HTML
  CHANGELOG.md
  src/Writers/HTMLWriter.jl
  test/examples/src/man/tutorial.md
Labels: Status: Backport Needed, Type: Bug

#1517 Remove GitHub token build trigger warning
  docs/src/man/hosting.md
  src/deployconfig.jl
Labels: Status: Backport Needed, Type: Documentation, Type: Maintenance

#1526 Just warn if doctest() fails to clean up
  CHANGELOG.md
  src/Documenter.jl
Labels: Status: Backport Needed

#1527 A few PDF improvements
  CHANGELOG.md
  src/Writers/LaTeXWriter.jl
Labels: Format: LaTeX, Status: Backport Needed, Type: Enhancement

#1525 Backports for 0.26.2
  .appveyor.yml
  .github/workflows/CI.yml
  .travis.yml
  CHANGELOG.md
  Project.toml
  docs/src/man/hosting.md
  src/DocTests.jl
  src/Documenter.jl
  src/Writers/HTMLWriter.jl
  src/Writers/LaTeXWriter.jl
  src/deployconfig.jl
  test/doctests/doctests.jl
  test/doctests/fix/tests.jl
  test/doctests/src/working.md
  test/examples/src/man/tutorial.md
Labels: Type: Backport

#1529 Make deploydocs throw if push fails
  CHANGELOG.md
  src/Documenter.jl
Labels: Type: Enhancement

#1528 Remove unused fallback method for post_status
  src/deployconfig.jl
Labels: Type: Maintenance

#1533 Thrown an error if the repo path contains the protocol
  CHANGELOG.md
  src/Documenter.jl
  test/deployconfig.jl
Labels: Type: Bug
