Repository JuliaDocs/Documenter.jl, pull requests merged in 2021-06, with the labels that each got.

#1586 Change Julia v1.4 -> v1.6 in Travis CI/Github Actions workflows
  docs/src/man/hosting.md
Labels: Type: Documentation

#1588 Adds GeophysicalFlows.jl in Registered packges
  docs/src/man/examples.md
Labels: Type: Documentation

#1589 Fix links to fix linkcheck
  docs/src/contributing.md
  docs/src/man/examples.md
  docs/src/man/hosting.md
  src/Utilities/JSDependencies.jl
  src/deployconfig.jl
Labels: Type: Documentation, Type: Maintenance

#1577 Add warning for outdated docs
  CHANGELOG.md
  assets/html/scss/documenter/components/_admonition.scss
  assets/html/scss/documenter/components/_all.scss
  assets/html/scss/documenter/components/_warner.scss
  assets/html/themes/documenter-dark.css
  assets/html/themes/documenter-light.css
  assets/html/warner.js
  docs/Project.toml
  docs/src/lib/public.md
  src/Documenter.jl
  src/Writers/HTMLWriter.jl
  test/examples/tests.jl
Labels: Format: HTML, Type: Feature

#1592 remove note in README about pre 1.0 versions
  README.md
Labels: Type: Documentation

#1559 Update from analytics.js to gtag.js
  CHANGELOG.md
  src/Writers/HTMLWriter.jl
Labels: Format: HTML, Type: Enhancement

#1590 Set version to 0.27.0
  CHANGELOG.md
  Project.toml
  assets/html/scss/highlightjs/a11y-dark.css
  assets/html/scss/highlightjs/default.css
  assets/html/themes/documenter-dark.css
  assets/html/themes/documenter-light.css
  docs/Project.toml
  src/Writers/HTMLWriter.jl
  test/themes/Project.toml
Labels: Type: Maintenance

#1597 Update examples.md
  docs/src/man/examples.md
Labels: Type: Documentation

#1596 check for empty entries in generate_version_file
  CHANGELOG.md
  src/Writers/HTMLWriter.jl
Labels: Format: HTML, Type: Bug

#1598 Document behavior of thrown exceptions in `@repl`
  docs/src/man/syntax.md
Labels: Type: Documentation

#1595 Adjust wording of outdated warning
  CHANGELOG.md
  assets/html/warner.js
Labels: Format: HTML, Type: Enhancement

#1569 Use JuliaMono, drop Google Fonts CDN
  CHANGELOG.md
  assets/html/scss/documenter-dark.scss
  assets/html/scss/documenter/_variables.scss
  assets/html/themes/documenter-dark.css
  assets/html/themes/documenter-light.css
  src/Writers/HTMLWriter.jl
  test/examples/make.jl
  test/examples/src/fonts.md
  test/examples/tests.jl
Labels: Format: HTML, Type: Enhancement

#1599 Set version to 0.27.1
  .github/workflows/CI.yml
  Project.toml
Labels: Type: Maintenance

#1604 Use 'Lato Medium' as the primary font
  CHANGELOG.md
  Project.toml
  assets/html/scss/documenter-dark.scss
  assets/html/scss/documenter/_variables.scss
  assets/html/themes/documenter-dark.css
  assets/html/themes/documenter-light.css
Labels: Format: HTML, Type: Enhancement

#1609 Display Documenter version in document build info.
  CHANGELOG.md
  src/Writers/HTMLWriter.jl
Labels: Format: HTML, Type: Enhancement

#1607 Related packages
  README.md
Labels: Type: Documentation

#1611 Move definition of Documenter version to precompilation-time.
  CHANGELOG.md
  src/Documenter.jl
  src/Writers/HTMLWriter.jl
Labels: Type: Enhancement

#1617 Disable JuliaMono ligatures
  CHANGELOG.md
  assets/html/scss/documenter/_patches.scss
  assets/html/themes/documenter-dark.css
  assets/html/themes/documenter-light.css
Labels: Format: HTML, Type: Bug

#1616 Support deployment to the root instead of to a version subfolder
  CHANGELOG.md
  docs/src/man/hosting.md
  src/Documenter.jl
  src/deployconfig.jl
Labels: Type: Feature
