Repository JuliaDocs/Documenter.jl, pull requests merged in 2022-10, with the labels that each got.

#1957 Switch to use {minted} for code output in LaTeXWriter
  CHANGELOG.md
  assets/latex/documenter.sty
  src/Writers/LaTeXWriter.jl
  test/examples/references/latex_showcase.tex
  test/examples/src.latex_showcase/showcase.md
Labels: Format: LaTeX

#1964 Don't throw in source_url() due to a non-existing source file
  src/Utilities/Utilities.jl
Labels: Type: Bugfix

#1923 fix error in relpath_from_repo_root when file not exists
  src/Utilities/Utilities.jl
  test/utilities.jl
Labels: Type: Bugfix

#1972 Work around a Git default configuration change
  test/utilities.jl
Labels: Type: Maintenance, Type: Tests

#1970 Expand code-like blocks in nested contexts
  CHANGELOG.md
  src/Expanders.jl
  src/Utilities/Selectors.jl
  test/examples/make.jl
  test/examples/src/issue491.md
  test/examples/tests.jl
Labels: Type: Enhancement

#1973 Implement JuliaValue for writers
  src/Writers/HTMLWriter.jl
  src/Writers/LaTeXWriter.jl
  test/examples/src/index.md
Labels: Format: LaTeX, Format: HTML, Type: Bugfix

#1974 Add WorldDynamics.jl to the list of Examples
  docs/src/man/examples.md
Labels: Type: Documentation
