Repository JuliaDocs/Documenter.jl, pull requests merged in 2022-07, with the labels that each got.

#1860 Edit LaTeX customization docs
  docs/src/man/other-formats.md
Labels: Type: Documentation

#1861 Fix missing doc check for methods from other packages
  CHANGELOG.md
  src/DocChecks.jl
  test/docchecks.jl
  test/missingdocs/make.jl
  test/missingdocs/src/all/index.md
  test/runtests.jl
Labels: Status: Backport Needed, Type: Bugfix

#1862 Set GIT_TEMPLATE_DIR when calling Git
  CHANGELOG.md
  src/Documenter.jl
  src/Utilities/Utilities.jl
  test/doctests/doctests.jl
  test/utilities.jl
Labels: Status: Backport Needed, Type: Bugfix

#1864 Change minimum Julia version 1.0 -> 1.6 in README
  README.md
Labels: Type: Documentation

#1865 Allow "deploying" to a tarball
  CHANGELOG.md
  src/Documenter.jl
  test/deploydocs.jl
  test/runtests.jl
Labels: Type: Feature, Status: Backport Needed

#1866 Backports for 0.27.20
  CHANGELOG.md
  Project.toml
  docs/src/man/examples.md
  src/DocChecks.jl
  src/DocSystem.jl
  src/Documenter.jl
  src/Utilities/Utilities.jl
  src/Writers/HTMLWriter.jl
  src/Writers/LaTeXWriter.jl
  test/deploydocs.jl
  test/docchecks.jl
  test/docsystem.jl
  test/doctests/doctests.jl
  test/doctests/src/working.md
  test/missingdocs/make.jl
  test/missingdocs/src/all/index.md
  test/prerender/prerender.jl
  test/runtests.jl
  test/utilities.jl
Labels: Type: Backport

#1867 Merge CI jobs into single workflow
  .github/workflows/CI.yml
  .github/workflows/linkcheck.yml
  .github/workflows/repochecks.yml
Labels: Type: Maintenance

#1873 Fix nightly tests
  test/errors/make.jl
Labels: Type: Tests

#1871 Handle missing Git in git_remote_head_branch
  CHANGELOG.md
  src/Utilities/Utilities.jl
Labels: Type: Bugfix

#1875 Regenerate favicon to increase resolution.
  docs/src/assets/favicon.ico
Labels: Type: Documentation

#1874 Backports for 0.27.21
  .github/workflows/CI.yml
  .github/workflows/linkcheck.yml
  .github/workflows/repochecks.yml
  CHANGELOG.md
  Project.toml
  docs/src/assets/favicon.ico
  src/Utilities/Utilities.jl
  test/deploydocs.jl
  test/errors/make.jl
Labels: Type: Backport

#1876 Use DocumenterTools as a dev dep in docs/
  .github/workflows/CI.yml
  .gitignore
  Project.toml
  docs/Project.toml
  docs/instantiate.jl
  test/themes/Project.toml
Labels: Type: Documentation

#1808 Refactor the repo/remote handling
  CHANGELOG.md
  docs/src/lib/internals/utilities.md
  docs/src/lib/public.md
  src/CrossReferences.jl
  src/Documenter.jl
  src/Documents.jl
  src/Utilities/Remotes.jl
  src/Utilities/Utilities.jl
  src/Writers/HTMLWriter.jl
  src/Writers/LaTeXWriter.jl
  test/examples/make.jl
  test/examples/src/editurl/bad.md
  test/examples/src/editurl/good.md
  test/examples/src/editurl/ugly.md
  test/remotes.jl
  test/runtests.jl
  test/utilities.jl
Labels: Type: Enhancement

#1882 Improve how the at-quietly logs are handled in the tests
  .gitignore
  test/TestUtilities.jl
  test/deploydocs.jl
  test/doctests/fix/tests.jl
  test/examples/make.jl
  test/missingdocs/make.jl
  test/runtests.jl
  test/utilities.jl
Labels: Type: Tests

#1254 Link to repo in navbar
  CHANGELOG.md
  assets/html/scss/documenter/layout/_main.scss
  assets/html/themes/documenter-dark.css
  assets/html/themes/documenter-light.css
  src/Writers/HTMLWriter.jl
  test/examples/make.jl
  test/htmlwriter.jl
Labels: Type: Enhancement, Format: HTML

#1881 Improve automatic Git remote detection
  CHANGELOG.md
  src/Documents.jl
  src/Utilities/Utilities.jl
  test/TestUtilities.jl
  test/examples/make.jl
  test/examples/tests.jl
  test/navnode.jl
Labels: Type: Enhancement, Type: Bugfix

#1880 add Woodpecker
  CHANGELOG.md
  docs/src/man/hosting.md
  docs/src/man/hosting/gitea-codeberg-add-deploy-key.png
  docs/src/man/hosting/walkthrough.md
  src/deployconfig.jl
  test/deployconfig.jl
Labels: Type: Enhancement

#1888 Add CHANGELOG for 0.27.22 to master
  CHANGELOG.md
Labels: Type: Documentation

#1887 Backports for 0.27.22
  .github/workflows/CI.yml
  CHANGELOG.md
  Project.toml
Labels: Type: Backport

#1890 Support UnitRange for Depth configuration in `at-contents` block
  CHANGELOG.md
  docs/src/lib/public.md
  docs/src/man/syntax.md
  src/Documents.jl
  src/Writers/HTMLWriter.jl
  src/Writers/LaTeXWriter.jl
Labels: Type: Enhancement
