Repository JuliaDocs/Documenter.jl, pull requests merged in 2022-08, with the labels that each got.

#1903 Add aria-label to copy code button for accessibility
  CHANGELOG.md
  assets/html/js/copy.js
Labels: Type: Enhancement, Format: HTML

#1904 Remove mktempdir override in LaTeXWriter
  src/Writers/LaTeXWriter.jl
  test/examples/mkdocs.yml
Labels: Type: Maintenance

#1907 Remove unused code paths related to DocsNode
  src/Writers/HTMLWriter.jl
  src/Writers/LaTeXWriter.jl
Labels: Type: Maintenance

#1906 Normalize line endings in MD source before parsing
  CHANGELOG.md
  src/Documents.jl
Labels: Type: Bugfix

#1900 Make at-ref links more flexible
  CHANGELOG.md
  docs/src/man/syntax.md
  src/CrossReferences.jl
  test/crossreferences.jl
  test/examples/make.jl
  test/examples/src/xrefs.md
  test/examples/tests.jl
  test/runtests.jl
Labels: Type: Enhancement

#1908 Various bugfixes and enhancements to LaTeXWriter
  CHANGELOG.md
  src/Writers/LaTeXWriter.jl
  test/examples/src.latex_simple/index.md
Labels: Type: Enhancement, Status: Backport Needed, Format: LaTeX

#1909 attempt to fix broken PDF links
  CHANGELOG.md
  assets/latex/documenter.sty
  src/Anchors.jl
  src/Writers/LaTeXWriter.jl
Labels: Format: LaTeX, Type: Bugfix

#1913 Backports for 0.27.23
  CHANGELOG.md
  assets/latex/documenter.sty
  src/Anchors.jl
  src/Writers/LaTeXWriter.jl
  test/examples/src.latex_simple/index.md
Labels: Type: Backport

#1892 Use MarkdownAST package for doctests
  CHANGELOG.md
  Project.toml
  docs/Project.toml
  docs/src/lib/internals/markdown2.md
  scripts/changelog.jl
  src/DocChecks.jl
  src/DocTests.jl
  src/Documents.jl
  src/Utilities/Markdown2.jl
  src/Utilities/Utilities.jl
  test/markdown2.jl
  test/runtests.jl
  test/utilities.jl
Labels: Type: Maintenance

#1915 Add CompatHelper workflow
  .github/workflows/CompatHelper.yml
Labels: Type: Maintenance

#1911 Remove the RawHTML document node
  src/Documents.jl
  src/Writers/HTMLWriter.jl
Labels: Type: Maintenance

#1905 Expand the LaTeXWriter integration tests
  .gitattributes
  src/Utilities/Utilities.jl
  src/Writers/LaTeXWriter.jl
  test/examples/make.jl
  test/examples/references/latex_showcase.tex
  test/examples/references/latex_simple.tex
  test/examples/src.latex_showcase/docstrings.md
  test/examples/src.latex_showcase/index.md
  test/examples/src.latex_showcase/logo.png
  test/examples/src.latex_showcase/showcase.md
  test/examples/tests.jl
  test/examples/tests_latex.jl
Labels: Type: Maintenance, Format: LaTeX
