Repository JuliaDocs/Documenter.jl, pull requests merged in 2022-12, with the labels that each got.

#1992 Add a few examples from SlimGroup
  docs/src/man/examples.md
Labels: Type: Documentation

#1989 Support regex => substitution pairs in doctest filters
  CHANGELOG.md
  docs/src/man/doctests.md
  src/DocTests.jl
  test/doctests/src/working.md
Labels: Type: Enhancement

#1995 Allow automated test missingdocs
  src/DocChecks.jl
  test/missingdocs/make.jl
Labels: Type: Maintenance

#1997 Include stacktraces in at-block code errors
  src/DocTests.jl
  src/Expanders.jl
  src/utilities/utilities.jl
  test/doctests/doctests.jl
  test/utilities.jl
Labels: Type: Enhancement

#1991 Add support for generating meta tags.
  CHANGELOG.md
  docs/src/assets/preview.png
  docs/src/man/syntax.md
  src/html/HTMLWriter.jl
  src/utilities/DOM.jl
  test/dom.jl
  test/examples/images/preview.png
  test/examples/make.jl
  test/examples/tests.jl
Labels: Type: Enhancement, Format: HTML

#1271 Allow replacements in doctest filters
  CHANGELOG.md
  docs/src/man/doctests.md
  src/DocTests.jl
  test/doctests/doctests.jl
  test/doctests/src/broken.md
  test/doctests/src/softscope.md
  test/doctests/src/working.md
  test/doctests/stdouts/12.stdout
  test/doctests/stdouts/2.stdout
  test/doctests/stdouts/22.stdout
  test/doctests/stdouts/23.stdout
  test/doctests/stdouts/24.stdout
  test/doctests/stdouts/25.stdout
  test/doctests/stdouts/31.stdout
  test/doctests/stdouts/4.stdout
  test/doctests/stdouts/5.stdout
  test/doctests/stdouts/6.stdout
  test/doctests/stdouts/8.stdout
Labels: Type: Enhancement
