Repository JuliaDocs/Documenter.jl, pull requests merged in 2022-06, with the labels that each got.

#1834 Hide sidebar on search
  CHANGELOG.md
  assets/html/search.js
Labels: Format: HTML, Type: Bugfix

#1830 Automatically determine edit_link default
  CHANGELOG.md
  src/Documenter.jl
  src/Utilities/Utilities.jl
  src/Writers/HTMLWriter.jl
  test/TestUtilities.jl
  test/doctests/doctests.jl
  test/utilities.jl
Labels: Type: Enhancement, Status: Backport Needed, Format: HTML

#1836 Draft mode that skips (potentially) expensive parts of the build process
  CHANGELOG.md
  docs/src/man/syntax.md
  src/DocTests.jl
  src/Documenter.jl
  src/Documents.jl
  src/Expanders.jl
  src/Utilities/Utilities.jl
  test/examples/make.jl
Labels: Type: Enhancement, Status: Backport Needed

#1838 Memoize result value in Utilities.getremote
  CHANGELOG.md
  scripts/changelog.jl
  src/Utilities/Utilities.jl
Labels: Type: Enhancement, Status: Backport Needed

#1841 Raise minimum required Julia version from 1.0 to 1.6
  .github/workflows/CI.yml
  CHANGELOG.md
  Project.toml
  src/DocTests.jl
  src/Expanders.jl
  src/Utilities/Utilities.jl
  src/Writers/LaTeXWriter.jl
  src/deployconfig.jl
  test/TestUtilities.jl
  test/doctests/doctests.jl
  test/doctests/fix/tests.jl
  test/doctests/src/hardscope.md
  test/utilities.jl
Labels: Type: Maintenance

#1844 Update MathJax to 3.2.2
  CHANGELOG.md
  src/Writers/HTMLWriter.jl
Labels: Type: Enhancement, Status: Backport Needed, Format: HTML

#1846 Update JS dependencies to latest non-breaking version
  CHANGELOG.md
  src/Writers/HTMLWriter.jl
  test/prerender/prerender.jl
Labels: Type: Enhancement, Format: HTML

#1842 Refactor `getdocs` code
  CHANGELOG.md
  src/DocSystem.jl
  test/docsystem.jl
Labels: Status: Backport Needed, Type: Bugfix

#1847 Update example link to SimGBS.jl
  docs/src/man/examples.md
Labels: Type: Documentation

#1853 change CI badges from Travis/AV -> GHA
  README.md
Labels: Type: Documentation

#1826 Remove Markdown backend from Documenter
  CHANGELOG.md
  Project.toml
  assets/mkdocs/Documenter.css
  assets/mkdocs/mathjaxhelper.js
  docs/src/lib/internals/writers.md
  docs/src/lib/public.md
  docs/src/man/other-formats.md
  src/Deps.jl
  src/Documenter.jl
  src/Utilities/Utilities.jl
  src/Writers/HTMLWriter.jl
  src/Writers/LaTeXWriter.jl
  src/Writers/MarkdownWriter.jl
  src/Writers/Writers.jl
  test/examples/make.jl
  test/examples/tests.jl
  test/formats/markdown.jl
  test/runtests.jl
Labels: Type: Breaking, Format: Markdown

#1856 Fix nightly test failures
  test/doctests/src/working.md
Labels: Type: Tests

#1858 GHA setup: add statuses write permissions
  docs/src/man/hosting.md
Labels: Type: Documentation
