Repository JuliaDocs/Documenter.jl, pull requests merged in 2023-07, with the labels that each got.

#2162 Backports for 0.27.25
  CHANGELOG.md
  Project.toml
  assets/html/scss/documenter-dark.scss
  assets/html/themes/documenter-dark.css
  assets/html/themes/documenter-light.css
  docs/Project.toml
  src/Writers/LaTeXWriter.jl
  test/doctests/doctestapi.jl
  test/examples/make.jl
  test/themes/Project.toml
  test/utilities.jl
  test/utilities.sample.jl
Labels: Type: Backport

#2163 docs: move backported changelog entries to correct version
  CHANGELOG.md
Labels: Type: Documentation

#2167 test: fix online linkchecks
  .github/workflows/CI.yml
  test/docchecks.jl
  test/online_linkcheck.jl
  test/run_docchecks.jl
Labels: Type: Tests

#2108 ci: generate better TagBot changelogs
  .github/workflows/TagBot.yml
Labels: Type: Maintenance

#2169 Fix the hamburger styling
  CHANGELOG.md
  assets/html/scss/documenter-dark.scss
  assets/html/scss/documenter/layout/_main.scss
  assets/html/themes/documenter-dark.css
  assets/html/themes/documenter-light.css
  src/html/HTMLWriter.jl
Labels: Format: HTML, Type: Bugfix

#2170 Add option to reset theme to OS preference
  CHANGELOG.md
  assets/html/js/themes.js
  assets/html/themeswap.js
  src/html/HTMLWriter.jl
Labels: Type: Enhancement, Format: HTML

#2081 Overhaul remote repository link handling
  CHANGELOG.md
  docs/make.jl
  docs/src/lib/public.md
  docs/src/lib/remote-links.md
  src/doctest.jl
  src/documents.jl
  src/html/HTMLWriter.jl
  src/latex/LaTeXWriter.jl
  src/makedocs.jl
  src/utilities/utilities.jl
  test/TestUtilities.jl
  test/examples/make.jl
  test/examples/references/latex_showcase.tex
  test/examples/src/editurl/bad.md
  test/examples/tests.jl
  test/nongit/docs/make.jl
  test/repolinks.jl
  test/runtests.jl
  test/utilities.jl
Labels: Type: Enhancement

#2176 add --project to julia command using --color
  docs/src/man/guide.md
Labels: Type: Documentation

#2174 Fix precompilation when package is not a dev dependency
  src/docs_precompile/make.jl
  src/documents.jl
Labels: Type: Bugfix

#2181 Add a siteinfo JSON file generated by makedocs
  CHANGELOG.md
  src/html/HTMLWriter.jl
  test/examples/tests.jl
Labels: Type: Enhancement, Format: HTML

#2185 add Oceananigans
  docs/src/man/examples.md
Labels: Type: Documentation

#2186 Add a prettier workflow to format JS
  .github/workflows/CI.yml
  .prettierignore
  .prettierrc
  assets/html/js/collapse.js
  assets/html/js/headroom.js
  assets/html/js/settings.js
  assets/html/js/sidebar.js
  assets/html/js/themes.js
  assets/html/js/versions.js
  assets/html/search.js
  assets/html/themeswap.js
  assets/html/warner.js
Labels: Type: Maintenance

#2184 Change the changelog infrastructure
  CHANGELOG.md
  Makefile
  docs/changelog.jl
  docs/make.jl
Labels: Type: Maintenance, Type: Documentation

#2188 Add NIST link to linkcheck ignore
  docs/make.jl
Labels: Type: Maintenance

#2191 Flatten CrossReferences module
  docs/src/lib/internals/cross-references.md
  docs/src/lib/internals/documenter.md
  src/Builder.jl
  src/Documenter.jl
  src/cross_references.jl
  test/crossreferences.jl
Labels: Type: Maintenance
