Repository JuliaDocs/Documenter.jl, pull requests merged in 2023-11, with the labels that each got.

#2325 Fix slugify removing leading numeric digits
  CHANGELOG.md
  src/utilities/utilities.jl
  test/utilities.jl
Labels: Type: Enhancement, Format: HTML

#2323 Add regression-tests.yml for manually testing dependent packages
  .github/workflows/regression-tests.yml
Labels: Type: Maintenance

#2328 Refactor "Doc Preview Cleanup" example workflow
  docs/src/man/hosting.md
Labels: Type: Documentation

#2330 Fix `linkcheck` for docstrings
  .github/workflows/CI.yml
  CHANGELOG.md
  src/docchecks.jl
  test/docstring_links/make.jl
  test/docstring_links/src/index.md
  test/online_linkcheck.jl
Labels: Type: Bugfix

#2313 added recursive list search for headings
  CHANGELOG.md
  docs/DocumenterShowcase.jl
  docs/src/showcase.md
  src/expander_pipeline.jl
Labels: Type: Bugfix

#2327 Improve the warning for an unexpected dollar sign in a Markdown file
  CHANGELOG.md
  src/html/HTMLWriter.jl
  src/latex/LaTeXWriter.jl
Labels: Type: Enhancement

#2352 docs: explicitly note previews aren't cleaned up and fix up markdown
  docs/src/man/hosting.md
  src/deploydocs.jl
Labels: Type: Documentation

#2354 Fix linkcheck warnings
  src/deployconfig.jl
  src/html/HTMLWriter.jl
Labels: Type: Maintenance, Type: Documentation

#2355 Fix doctests for nightly again
  docs/src/man/hosting.md
  src/deployconfig.jl
  test/doctests/stdouts/31.v1_11.stdout
Labels: Type: Maintenance

#2348 Use Git.jl for `git` operations
  CHANGELOG.md
  Project.toml
  src/Documenter.jl
  src/utilities/utilities.jl
Labels: Type: Enhancement

#2339 Add support for Woodpecker CI 1.x and 2.x
  CHANGELOG.md
  docs/src/man/hosting.md
  src/deployconfig.jl
  test/deployconfig.jl
Labels: Type: Enhancement

#2358 Revert "Disable coveralls submission in online linkcheck (#2347)"
  .github/workflows/CI.yml
Labels: Type: Maintenance

#2239 Use Changelog.jl for changelog infrastructure.
  CHANGELOG.md
  Makefile
  docs/Project.toml
  docs/changelog.jl
  docs/make.jl
Labels: Type: Documentation

#2361 ci: set Coveralls jobs `continue-on-failure: true`
  .github/workflows/CI.yml
Labels: Type: Maintenance

#2322 Add checklists.md to the documentation
  docs/make.jl
  docs/src/checklists.md
Labels: Type: Documentation

#2362 Set version to 1.2.0
  CHANGELOG.md
  Project.toml
  docs/src/checklists.md
Labels: Type: Maintenance
