Repository JuliaDocs/Documenter.jl, pull requests merged in 2023-03, with the labels that each got.

#2064 Update examples.md
  docs/src/man/examples.md
Labels: Type: Documentation

#2066 Bump KaTeX from `v0.13.24` to `v0.16.4`
  CHANGELOG.md
  src/html/HTMLWriter.jl
  src/html/RD.jl
Labels: Format: HTML

#2068 Remove .mapping field from Page
  src/Expanders.jl
  src/documents.jl
  test/utilities.jl
Labels: Type: Maintenance

#2067 Update JS deps to latest non-breaking version
  CHANGELOG.md
  assets/html/scss/highlightjs/a11y-dark.css
  assets/html/scss/highlightjs/default.css
  assets/html/themes/documenter-dark.css
  assets/html/themes/documenter-light.css
  src/html/RD.jl
Labels: Format: HTML

#2084 Fix typo in internal docstring
  src/DocSystem.jl
Labels: Type: Documentation

#2086 Clean docstrings
  docs/instantiate.jl
  docs/make.jl
  docs/src/man/latex.md
  src/Anchors.jl
  src/CrossReferences.jl
  src/DocChecks.jl
  src/DocSystem.jl
  src/latex/LaTeXWriter.jl
  src/utilities/DOM.jl
  src/utilities/Remotes.jl
Labels: Type: Documentation
