Repository JuliaDocs/Documenter.jl, pull requests merged in 2023-10, with the labels that each got.

#2289 Update examples.md
  docs/src/man/examples.md
Labels: Type: Documentation

#2294 Update link in README to DocumenterCitations
  README.md
Labels: Type: Documentation

#2295 Update examples.md: add Pigeons.jl
  docs/src/man/examples.md
Labels: Type: Documentation

#2297 Update URL in documentation
  docs/src/man/hosting.md
Labels: Type: Documentation

#2298 Update GeoStats docs URL
  docs/src/man/examples.md
Labels: Type: Documentation

#2217 Fixed docstring collapse/expand icon not changing when clicking rapidly
  CHANGELOG.md
  Project.toml
  assets/html/js/collapse.js
  assets/html/scss/documenter-dark.scss
  assets/html/scss/documenter-light.scss
  assets/html/themes/documenter-dark.css
  assets/html/themes/documenter-light.css
Labels: Format: HTML, Type: Bugfix

#2305 Add compats for standard libraries
  Project.toml
Labels: Type: Maintenance

#2300 Write non-breaking space as "~" in LaTeXWriter
  CHANGELOG.md
  Project.toml
  src/latex/LaTeXWriter.jl
  test/examples/references/latex_simple.tex
  test/examples/src.latex_simple/index.md
  test/latexwriter.jl
Labels: Format: LaTeX, Type: Bugfix

#2307 Fix: Enable text wrapping in docstring header on smaller screens (#2293)
  CHANGELOG.md
  assets/html/scss/documenter/components/_docstring.scss
  assets/html/themes/documenter-dark.css
  assets/html/themes/documenter-light.css
Labels: Format: HTML, Type: Bugfix

#2316 Add KaTeX example configuration example to docs
  docs/src/man/latex.md
Labels: Type: Documentation

#2317 Fix breadcrumb overflow on narrow screens
  CHANGELOG.md
  assets/html/scss/documenter/layout/_main.scss
  assets/html/themes/documenter-dark.css
  assets/html/themes/documenter-light.css
Labels: Format: HTML, Type: Bugfix
