Repository JuliaDocs/Documenter.jl, pull requests merged in 2023-08, with the labels that each got.

#2197 Fix Prettier action when running PRs
  .github/workflows/CI.yml
Labels: Type: Maintenance

#2198 Fix image and link references in LaTeXWriter
  .github/workflows/CI.yml
  src/documents.jl
  src/latex/LaTeXWriter.jl
Labels: Format: LaTeX

#2196 Use PrecompileTools
  Project.toml
  src/Documenter.jl
Labels: Type: Maintenance

#2172 Change from LunrJs to MinisearchJs for client-side search
  CHANGELOG.md
  assets/html/scss/documenter-dark.scss
  assets/html/scss/documenter-light.scss
  assets/html/scss/documenter/_variables.scss
  assets/html/scss/documenter/layout/_search.scss
  assets/html/search.js
  assets/html/themes/documenter-dark.css
  assets/html/themes/documenter-light.css
  src/html/HTMLWriter.jl
  src/html/RD.jl
Labels: Type: Enhancement, Format: HTML

#2209 docs: fix GitHub link 301
  docs/src/contributing.md
Labels: Type: Maintenance, Type: Documentation

#2194 Replace `strict` with `warnonly` and make `makedocs` builds fail by default
  CHANGELOG.md
  docs/make.jl
  docs/src/man/doctests.md
  src/Builder.jl
  src/documents.jl
  src/makedocs.jl
  src/utilities/utilities.jl
  test/doctests/doctests.jl
  test/errors/make.jl
  test/examples/make.jl
  test/missingdocs/make.jl
  test/online_linkcheck.jl
  test/utilities.jl
Labels: Type: Enhancement, Type: Breaking

#2205 Implement size threshold for HTML pages
  CHANGELOG.md
  src/html/HTMLWriter.jl
  test/examples/make.jl
  test/examples/src.megapage/index.md
  test/examples/tests.jl
  test/htmlwriter.jl
Labels: Type: Enhancement, Type: Breaking, Format: HTML

#2213 Update JS & font dependencies
  CHANGELOG.md
  src/html/RD.jl
Labels: Type: Enhancement, Format: HTML

#2214 Remove more of the internal modules
  CHANGELOG.md
  docs/src/lib/internals/anchors.md
  docs/src/lib/internals/builder.md
  docs/src/lib/internals/docchecks.md
  docs/src/lib/internals/doctests.md
  docs/src/lib/internals/expanders.md
  docs/src/man/doctests.md
  src/Documenter.jl
  src/anchors.jl
  src/builder_pipeline.jl
  src/cross_references.jl
  src/docchecks.jl
  src/doctests.jl
  src/documents.jl
  src/expander_pipeline.jl
  src/html/HTMLWriter.jl
  src/latex/LaTeXWriter.jl
  test/docchecks.jl
  test/doctests/doctests.jl
  test/doctests/stdouts/12.stdout
  test/doctests/stdouts/2.stdout
  test/doctests/stdouts/22.stdout
  test/doctests/stdouts/23.stdout
  test/doctests/stdouts/24.stdout
  test/doctests/stdouts/25.stdout
  test/doctests/stdouts/31.stdout
  test/doctests/stdouts/4.stdout
  test/doctests/stdouts/5.stdout
  test/doctests/stdouts/6.stdout
  test/doctests/stdouts/8.stdout
  test/missingdocs/make.jl
  test/navnode.jl
  test/online_linkcheck.jl
  test/pipeline.jl
Labels: Type: Maintenance

#2218 Fix 'UndefVarError: remote not defined'
  src/documents.jl
Labels: Type: Bugfix

#2219 Fix 'UndefVarError: remote not defined' v2
  src/documents.jl
Labels: Type: Bugfix

#2222 Add PkgEval badge to README
  README.md
Labels: Type: Documentation

#2223 fixed text not in warning box
  docs/src/man/hosting.md
Labels: Type: Documentation

#2227 Fix typo in CHANGELOG.md
  CHANGELOG.md
Labels: Type: Documentation

#2216 Fix extra spacing in nav bar
  CHANGELOG.md
  assets/html/scss/documenter/layout/_main.scss
  assets/html/themes/documenter-dark.css
  assets/html/themes/documenter-light.css
Labels: Type: Enhancement, Format: HTML

#2230 test: fix doctestapi tests
  test/doctests/doctestapi.jl
Labels: Type: Maintenance, Type: Tests

#2220 Print more information if unable to determine remote URL
  docs/src/lib/public.md
  src/documents.jl
  src/makedocs.jl
  test/repolinks.jl
Labels: Type: Enhancement

#2202 New Search Modal UI
  CHANGELOG.md
  assets/html/js/shortcut.js
  assets/html/scss/documenter-dark.scss
  assets/html/scss/documenter/_variables.scss
  assets/html/scss/documenter/layout/_search.scss
  assets/html/scss/documenter/layout/_sidebar.scss
  assets/html/search.js
  assets/html/themes/documenter-dark.css
  assets/html/themes/documenter-light.css
  src/html/HTMLWriter.jl
Labels: Type: Enhancement, Format: HTML

#2236 Remove search.js as separate overridable asset
  CHANGELOG.md
  assets/html/js/search.js
  docs/src/man/guide.md
  src/html/HTMLWriter.jl
  test/examples/src/assets/search.js
Labels: Type: Maintenance, Type: Breaking, Format: HTML

#2235 Improve contrast of the search placeholder text
  assets/html/scss/documenter-dark.scss
  assets/html/scss/documenter/_variables.scss
  assets/html/scss/documenter/layout/_sidebar.scss
  assets/html/themes/documenter-dark.css
  assets/html/themes/documenter-light.css
  docs/versions.js
Labels: Type: Enhancement, Format: HTML

#2231 docs: update remote links CHANGELOG entry
  CHANGELOG.md
Labels: Type: Documentation
