Repository JuliaDocs/Documenter.jl, pull requests merged in 2023-01, with the labels that each got.

#1993 Support custom tag prefix for release docs
  CHANGELOG.md
  docs/src/man/hosting.md
  src/deployconfig.jl
  src/deploydocs.jl
  test/deployconfig.jl
  test/deploydocs.jl
Labels: Type: Enhancement

#1950 Try Coveralls for code coverage
  .github/workflows/CI.yml
Labels: Type: Maintenance

#2012 catch existing symlinks when adding new ones
  CHANGELOG.md
  src/deploydocs.jl
Labels: Type: Bugfix

#2014 Remove pirated method from Expanders.jl
  Project.toml
  src/Expanders.jl
Labels: Type: Bugfix

#2011 Fix expanding of x-ref targets containing a code block
  test/examples/src/xrefs.md
Labels: Type: Tests

#2015 Fix oversights from removing Utilities module
  src/DocTests.jl
Labels: Type: Maintenance

#2018 Explicitly avoid committing SSH key to gh-pages
  CHANGELOG.md
  src/deploydocs.jl
Labels: Status: Backport Needed, Type: Bugfix

#2019 deploydocs: check that target is subdirectory of root
  CHANGELOG.md
  src/deploydocs.jl
Labels: Type: Enhancement

#2021 Backports for 0.27.24
  CHANGELOG.md
  Project.toml
  src/Documenter.jl
  test/doctests/doctests.jl
  test/doctests/src/softscope.md
  test/utilities.jl
Labels: Type: Backport
