Repository JuliaDocs/Documenter.jl, pull requests merged in 2023-09, with the labels that each got.

#2168 Documenter semver guarantee docs
  docs/make.jl
  docs/src/lib/semver.md
Labels: Type: Documentation

#2252 Add `size_threshold_ignore` to `HTML`
  CHANGELOG.md
  src/html/HTMLWriter.jl
  test/examples/make.jl
  test/examples/tests.jl
Labels: Type: Enhancement

#2249 Revise Plugins API, add `plugins` keyword arg for `makedocs` and `doctest`
  .gitignore
  CHANGELOG.md
  src/Documenter.jl
  src/doctest.jl
  src/documents.jl
  src/makedocs.jl
  test/plugins/make.jl
  test/plugins/src/index.md
  test/runtests.jl
Labels: Type: Enhancement, Type: Breaking

#2232 Automatically get remote for Pkg.add(...) packages
  CHANGELOG.md
  Project.toml
  docs/src/lib/remote-links.md
  src/Documenter.jl
  src/builder_pipeline.jl
  src/docchecks.jl
  src/documents.jl
  src/utilities/utilities.jl
  test/docchecks.jl
  test/online_githubcheck.jl
  test/repolink_helpers.jl
  test/repolinks.jl
Labels: Type: Enhancement

#2247 feat: write at-example outputs over threshold to a file
  CHANGELOG.md
  Project.toml
  src/html/HTMLWriter.jl
  test/examples/images/big.gif
  test/examples/images/big.png
  test/examples/images/big.svg
  test/examples/images/big.webp
  test/examples/images/tiny.jpeg
  test/examples/images/tiny.png
  test/examples/images/tiny.webp
  test/examples/make.jl
  test/examples/references/latex_showcase.tex
  test/examples/references/latex_simple.tex
  test/examples/src/example-output.md
  test/examples/src/index.md
  test/examples/src/outputs/index.md
  test/examples/src/outputs/outputs.md
  test/examples/tests.jl
Labels: Type: Enhancement, Format: HTML

#2256 Ignore size of release notes page in manual
  docs/make.jl
Labels: Type: Documentation

#2259 Throw an error if makedocs() gets passed invalid kwargs
  CHANGELOG.md
  src/documents.jl
  src/utilities/utilities.jl
  test/doctests/doctests.jl
  test/doctests/fix/tests.jl
Labels: Type: Breaking

#2260 Make at-eval type error a docerror
  CHANGELOG.md
  src/expander_pipeline.jl
  test/examples/make.jl
Labels: Type: Breaking

#2261 Move "Fix broken releases" into its own subsection
  docs/src/man/hosting.md
Labels: Type: Documentation

#2237 Add @(auto)docs secondary
  CHANGELOG.md
  docs/src/man/syntax.md
  docs/src/showcase.md
  src/docchecks.jl
  src/documents.jl
  src/expander_pipeline.jl
  src/utilities/utilities.jl
  test/examples/src/lib/functions.md
Labels: Type: Enhancement

#2228 Set version to 1.0.0
  CHANGELOG.md
  Project.toml
  docs/instantiate.jl
Labels: Type: Maintenance

#2267 Fix up 1.0 CHANGELOG entry
  CHANGELOG.md
Labels: Type: Documentation

#2269 fix: handle unwrapped MD objects in docstrings
  CHANGELOG.md
  src/DocSystem.jl
  src/doctests.jl
  src/expander_pipeline.jl
  test/docsystem.jl
  test/examples/make.jl
Labels: Type: Bugfix

#2275 hosting.md: recommend current codecov/codecov-action version
  docs/src/man/hosting.md
Labels: Type: Documentation

#2284 Update DemoCards.jl url
  README.md
Labels: Type: Documentation

#2285 Stop githubcheck() error when remotes is nothing
  CHANGELOG.md
  src/docchecks.jl
Labels: Type: Bugfix

#2281 Fix in-line math output in HTMLWriter
  CHANGELOG.md
  src/html/HTMLWriter.jl
  test/examples/src/man/tutorial.md
  test/htmlwriter.jl
Labels: Format: HTML, Type: Bugfix

#2279 Add an implementation of Remote for GitLab
  CHANGELOG.md
  docs/src/lib/remote-links.md
  src/utilities/Remotes.jl
  test/remotes.jl
Labels: Type: Enhancement
