Repository JuliaDocs/Documenter.jl, pull requests merged in 2024-02, with the labels that each got.

#2437 Improve repo path error message
  src/deploydocs.jl
Labels: Status: Approved

#2429 Add `/docs` project to installation instructions
  docs/src/man/guide.md
Labels: Type: Documentation

#2438 Fix theme selector picking the wrong entry
  CHANGELOG.md
  src/html/HTMLWriter.jl
Labels: Format: HTML, Type: Bugfix

#2394 Add support for `CollapsedDocStrings` in `@meta` block
  CHANGELOG.md
  assets/html/js/collapse.js
  assets/html/js/metadata.js
  docs/src/lib/internals/anchors.md
  docs/src/lib/internals/builder.md
  docs/src/lib/internals/docchecks.md
  docs/src/lib/internals/docmeta.md
  docs/src/lib/internals/docsystem.md
  docs/src/lib/internals/doctests.md
  docs/src/lib/internals/documenter.md
  docs/src/lib/internals/documentertools.md
  docs/src/lib/internals/documents.md
  docs/src/lib/internals/dom.md
  docs/src/lib/internals/expanders.md
  docs/src/lib/internals/jsdependencies.md
  docs/src/lib/internals/mdflatten.md
  docs/src/lib/internals/selectors.md
  docs/src/lib/internals/textdiff.md
  docs/src/lib/internals/utilities.md
  docs/src/lib/internals/writers.md
  docs/src/man/syntax.md
  docs/src/showcase.md
  src/expander_pipeline.jl
  src/html/HTMLWriter.jl
  test/examples/src/lib/functions.md
  test/examples/tests.jl
Labels: Type: Feature

#2415 Optimize search (8x speedup)
  CHANGELOG.md
  assets/html/js/search.js
  src/html/HTMLWriter.jl
  src/html/RD.jl
Labels: Type: Enhancement, Format: HTML

#2445 Remove duplicate word in warning
  src/html/HTMLWriter.jl
Labels: Type: Enhancement

#2453 Refactor `crossref`/`xref` for resolving `@ref` links
  docs/src/lib/internals/crossref.md
  docs/src/lib/internals/deploydocs.md
  src/cross_references.jl
Labels: Type: Maintenance, Type: Enhancement

#2447 CI check to enforce CHANGELOG changes
  .github/workflows/Changelog.yml
Labels: Type: Maintenance, Skip Changelog

#2466 Fix nightly tests
  test/doctests/src/softscope.v1_11.md
Labels: Type: Tests, Skip Changelog

#2461 Fix escaping special html entites in search output
  CHANGELOG.md
  assets/html/js/search.js
Labels: Format: HTML, Type: Bugfix

#2467 Extend compat for DocInventories to v0.4
  Project.toml
Labels: Skip Changelog
