Repository JuliaDocs/Documenter.jl, pull requests merged in 2024-05, with the labels that each got.

#2497 Use link-hover color also for (inline) code in links.
  CHANGELOG.md
  assets/html/scss/documenter/_patches.scss
  assets/html/themes/documenter-dark.css
  assets/html/themes/documenter-light.css
Labels: Format: HTML

#2498 Set version to 1.4.1
  CHANGELOG.md
  Project.toml
Labels: Type: Maintenance

#2500 Remove archived DocumenterLaTeX from docpage
  docs/src/man/other-formats.md
Labels: Skip Changelog

#2503 Fix backtick typo in HTMLWriter.jl
  src/html/HTMLWriter.jl
Labels: Type: Documentation

#2510 Call new theme Makefile from main one, add CI
  .github/workflows/CI.yml
  Makefile
  assets/html/Makefile
  assets/html/Project.toml
  assets/html/themes/catppuccin-frappe.css
  assets/html/themes/catppuccin-latte.css
  assets/html/themes/catppuccin-macchiato.css
  assets/html/themes/catppuccin-mocha.css
  assets/html/verify.jl
  test/themes/Project.toml
  test/themes/themes.jl
Labels: Type: Maintenance, Skip Changelog
