Repository JuliaDocs/Documenter.jl, pull requests merged in 2024-06, with the labels that each got.

#2520 Declare compatibility with DocInventories 1.0
  Project.toml
Labels: Type: Maintenance

#2525 Clean up admonition variables in catppuccin theme
  assets/html/scss/catppuccin.scss
  assets/html/scss/documenter/components/_admonition.scss
Labels: Type: Maintenance, Skip Changelog

#2513 Escape single paranthesis
  CHANGELOG.md
  assets/html/js/search.js
Labels: Format: HTML, Type: Bugfix

#2530 Fix typo
  src/deploydocs.jl
Labels: Skip Changelog

#2534 ci: make on:push CI trigger on a suffix
  .github/workflows/CI.yml
Labels: Skip Changelog

#2535 docs: fix PhyloNetworks docs URL
  docs/src/man/examples.md
Labels: Type: Documentation

#2539 docs: add name block examples to showcase.md
  docs/src/man/syntax.md
  docs/src/showcase.md
Labels: Type: Documentation, Skip Changelog
