Repository JuliaDocs/Documenter.jl, pull requests merged in 2024-11, with the labels that each got.

#2597 Reorganize online tests
  .github/workflows/CI.yml
  test/docchecks.jl
  test/online/Project.toml
  test/online/docstring_links/make.jl
  test/online/docstring_links/src/index.md
  test/online/online_githubcheck.jl
  test/online/online_linkcheck.jl
  test/online/runtests.jl
Labels: Type: Tests, Skip Changelog

#2598 Test failing online check against a mock HTTP server
  test/online/Project.toml
  test/online/online_linkcheck.jl
Labels: Type: Tests, Skip Changelog

#2599 Fix nightly CI by fixing example docstring Markdown
  test/examples/make.jl
  test/examples/references/latex_showcase.tex
  test/examples/references/latex_simple.tex
Labels: Type: Tests, Skip Changelog

#2590 add PauliStrings.jl to examples.md
  docs/src/man/examples.md
Labels: Type: Documentation, Skip Changelog

#2593 Fix the race condition causing search not to initialize properly
  CHANGELOG.md
  assets/html/js/search.js
Labels: Format: HTML, Type: Bugfix

#2600 Set version to 1.8.0
  CHANGELOG.md
  Project.toml
Labels: Type: Maintenance

#2607 Merge CI workflows into CI.yml, workflow_dispatch
  .github/workflows/CI.yml
  .github/workflows/Runic.yml
  .github/workflows/SpellCheck.yml
Labels: Type: Maintenance, Skip Changelog

#2612 Typo in makedocs docstring
  src/makedocs.jl
Labels: Skip Changelog
