Repository JuliaDocs/Documenter.jl, pull requests merged in 2024-08, with the labels that each got.

#2555 Fix libsass_jll to 3.6.4
  assets/html/Project.toml
Labels: Type: Maintenance, Skip Changelog

#2554 Fix typo in a comment
  src/expander_pipeline.jl
Labels: Type: Maintenance, Skip Changelog

#2553 Add `actions: write` permissions to example Actions workflow
  docs/src/man/hosting.md
Labels: Type: Documentation, Skip Changelog

#2551 Fix collapse work on icon and empty area only
  CHANGELOG.md
  assets/html/js/collapse.js
  src/html/HTMLWriter.jl
Labels: Format: HTML, Type: Bugfix

#2549 Use tex-svg-full.js for MathJax3
  CHANGELOG.md
  src/html/HTMLWriter.jl
  src/html/RD.jl
Labels: Type: Enhancement, Format: HTML

#2558 Set version to 1.6.0
  CHANGELOG.md
  Project.toml
Labels: Type: Maintenance

#2565 Update hosting.md
  docs/src/man/hosting.md
Labels: Type: Documentation, Skip Changelog
