Repository JuliaDocs/Documenter.jl, pull requests merged in 2024-03, with the labels that each got.

#2457 Allow customizing domain in deploydocs
  docs/src/man/hosting.md
  src/deploydocs.jl
  test/deploydocs.jl
Labels: Status: Approved

#2431 Document `makedocs` argument `pages` for LaTeX output
  docs/src/man/other-formats.md
Labels: Format: LaTeX, Type: Bugfix, Skip Changelog

#2468 Set version to 1.3.0
  CHANGELOG.md
  Project.toml
Labels: Type: Maintenance

#2469 Minor editorial-type fixes in docs
  docs/src/man/syntax.md
Labels: Type: Documentation, Skip Changelog

#2475 drop settings from `DCtx`
  src/html/HTMLWriter.jl
Labels: Type: Maintenance, Status: Approved, Skip Changelog

#2477 Add `DocumenterInterLinks` to regression tests
  .github/workflows/regression-tests.yml
Labels: Type: Maintenance, Skip Changelog

#2480 Consistency on `using` and qualified access
  src/html/HTMLWriter.jl
Labels: Type: Maintenance, Skip Changelog

#2470 Resolve `@ref` bindings in current module and `Main`
  CHANGELOG.md
  docs/src/man/syntax.md
  src/cross_references.jl
  test/docsxref/make.jl
  test/docsxref/src/index.md
  test/docsxref/src/page.md
  test/runtests.jl
Labels: Type: Enhancement

#2483 Fix Woodpecker 0.15.x docs link
  src/deployconfig.jl
Labels: Type: Documentation, Skip Changelog

#2478 Document required GitHub Action permissions
  docs/src/man/hosting.md
Labels: Type: Documentation, Skip Changelog
