Repository JuliaDocs/Documenter.jl, pull requests merged in 2024-09, with the labels that each got.

#2563 Add changelog section to contributing docs
  docs/src/contributing.md
Labels: Type: Documentation, Skip Changelog

#2561 Normalize the paths for `size_threshold_ignore`
  CHANGELOG.md
  src/html/HTMLWriter.jl
  test/examples/make.jl
  test/examples/src.megapage/subdir/subpage.md
Labels: Format: HTML, Type: Bugfix

#2568 Fix typo in _patches.scss
  assets/html/scss/documenter/_patches.scss
Labels: Type: Maintenance, Skip Changelog

#2562 Make user-agent for linkchecks customisable
  CHANGELOG.md
  src/docchecks.jl
  src/documents.jl
  src/makedocs.jl
  test/examples/make.jl
  test/examples/tests.jl
Labels: Type: Enhancement

#2526 Add purple coloring for todo-admonitions
  CHANGELOG.md
  assets/html/scss/catppuccin.scss
  assets/html/scss/documenter-dark.scss
  assets/html/scss/documenter-light.scss
  assets/html/scss/documenter/components/_admonition.scss
  assets/html/themes/catppuccin-frappe.css
  assets/html/themes/catppuccin-latte.css
  assets/html/themes/catppuccin-macchiato.css
  assets/html/themes/catppuccin-mocha.css
  assets/html/themes/documenter-dark.css
  assets/html/themes/documenter-light.css
  assets/latex/documenter.sty
  docs/src/showcase.md
  src/html/HTMLWriter.jl
  src/latex/LaTeXWriter.jl
Labels: Type: Enhancement, Format: HTML

#2377 Add checkdocs_ignored_modules to exclude certain modules from checkdocs
  CHANGELOG.md
  src/documents.jl
  src/makedocs.jl
  src/utilities/utilities.jl
  test/missingdocs/make.jl
Labels: Type: Enhancement

#2571 Fix linkcheck_useragent implementation and tests
  CHANGELOG.md
  src/docchecks.jl
  src/documents.jl
  src/makedocs.jl
  test/online_linkcheck.jl
Labels: Type: Tests, Type: Bugfix

#2570 Set version to 1.7.0
  CHANGELOG.md
  Project.toml
Labels: Type: Maintenance
