Repository JuliaDocs/Documenter.jl, pull requests merged in 2025-07, with the labels that each got.

#2749 Fix PDF/LaTeX CI
  .github/workflows/CI.yml
Labels: Type: Maintenance, Skip Changelog

#2748 Add `release` to allowed vals for `GITHUB_EVENT_NAME`
  CHANGELOG.md
  Project.toml
  src/deployconfig.jl
  test/deployconfig.jl
Labels: Type: Enhancement

#2740 Adding the complete architecture for search benchmarking
  .github/workflows/CI.yml
  Makefile
  Project.toml
  assets/html/js/search.js
  src/html/HTMLWriter.jl
  test/search/Project.toml
  test/search/evaluate.jl
  test/search/real_search.jl
  test/search/run_benchmarks.jl
  test/search/search_benchmark_reference.json
  test/search/test_queries.jl
  test/search/wrapper.js
Labels: Type: Tests, Format: HTML, Skip Changelog

#2754 Add .gitignore for search benchmark outputs
  test/search/.gitignore
Labels: Skip Changelog
