Repository JuliaDocs/Documenter.jl, pull requests merged in 2025-02, with the labels that each got.

#2625 test: fix JuliaSyntax & world age failures in tests
  test/TestUtilities.jl
  test/doctests/fix/tests.jl
  test/utilities.jl
Labels: Skip Changelog

#2626 docs: fix SimGBS.jl URL
  docs/src/man/examples.md
Labels: Skip Changelog

#2620 Mention at-id syntax in a heading in the docs
  docs/src/man/syntax.md
Labels: Type: Documentation, Skip Changelog

#2627 Set version to 1.8.1
  CHANGELOG.md
  Project.toml
Labels: Type: Maintenance

#2631 Tweak GitHub Actions documentation
  docs/src/man/hosting.md
Labels: Skip Changelog

#2634 Point Woodpecker 1.x docs to archive.org
  src/deployconfig.jl
Labels: Type: Documentation

#2636 Throw an informative error if `sitename` is missing when building LaTeX
  CHANGELOG.md
  src/latex/LaTeXWriter.jl
Labels: Type: Enhancement

#2619 Support substitutions in doctestfilters
  CHANGELOG.md
  src/doctest.jl
  src/documents.jl
  test/doctests/doctestapi.jl
Labels: Type: Enhancement

#2637 Fix the 301 redirect links in the manual
  docs/src/man/hosting.md
  src/deployconfig.jl
Labels: Type: Maintenance, Type: Documentation, Skip Changelog
