Repository JuliaDocs/Documenter.jl, pull requests merged in 2025-05, with the labels that each got.

#2693 Fix clear_module! world semantics
  CHANGELOG.md
  src/expander_pipeline.jl
Labels: Type: Bugfix

#2696 Add `make clean` target
  Makefile
Labels: Type: Maintenance, Skip Changelog

#2694 CI: run regression-tests.yml on all PRs & primary branches
  .github/workflows/regression-tests.yml
Labels: Type: Maintenance, Skip Changelog

#2689 CI: test building Oscar manual
  .github/workflows/regression-tests.yml
Labels: Skip Changelog

#2695 Dispatch logic on `versions` when deploying
  CHANGELOG.md
  src/deploydocs.jl
Labels: Type: Maintenance

#2701 Remove LibGit2 dependency
  CHANGELOG.md
  Project.toml
  src/utilities/utilities.jl
Labels: Type: Maintenance

#2706 Adapt wording regarding `deploy_repo` and `repo_preview`
  src/deploydocs.jl
Labels: Skip Changelog

#2705 Move some CHANGELOG entries into 'Added' section
  CHANGELOG.md
Labels: Type: Maintenance

#2707 Set version to 1.11.0
  CHANGELOG.md
  Project.toml
Labels: Type: Maintenance

#2713 ci: replace file with files in codecov
  .github/workflows/CI.yml
Labels: Skip Changelog

#2708 Fix LaTeXWriter with local images on Windows
  .github/workflows/CI.yml
  CHANGELOG.md
  src/latex/LaTeXWriter.jl
  test/examples/Project.toml
  test/examples/tests_latex.jl
Labels: Type: Bugfix

#2715 fix coverallsapp with parallel-finished
  .github/workflows/CI.yml
Labels: Skip Changelog

#2714 Use appropriate show method for PageLink
  CHANGELOG.md
  src/documents.jl
Labels: Type: Bugfix

#2716 Remove misleading remark about ./ paths in showcase.md
  docs/src/showcase.md
Labels: Type: Documentation, Skip Changelog

#2719 Add docs-warn-only command to Makefile
  Makefile
Labels: Type: Maintenance

#2720 Set version to 1.11.1
  CHANGELOG.md
  Project.toml
  docs/src/checklists.md
Labels: Type: Maintenance

#2721 Use symbol :display instead of function
  CHANGELOG.md
  Project.toml
  src/html/HTMLWriter.jl
Labels: Type: Bugfix

#2722 Fix non-standard versions in deploydocs
  CHANGELOG.md
  Project.toml
  src/deploydocs.jl
Labels: Type: Bugfix

#2723 Fix non-standard versions in deploydocs (v2)
  .github/workflows/CI.yml
  CHANGELOG.md
  Project.toml
  src/deploydocs.jl
Labels: Type: Bugfix
