Repository JuliaDocs/Documenter.jl, pull requests merged in 2025-04, with the labels that each got.

#2675 Remove at-meta, at-setup, at-docs from search index
  CHANGELOG.md
  src/html/HTMLWriter.jl
Labels: Format: HTML, Type: Bugfix

#2669 Add DocumenterPages.jl to regression tests
  .github/workflows/regression-tests.yml
Labels: Type: Maintenance, Skip Changelog

#2676 Added anchor links to admonition blocks for direct referencing
  CHANGELOG.md
  assets/html/scss/documenter/components/_admonition.scss
  assets/html/themes/catppuccin-frappe.css
  assets/html/themes/catppuccin-latte.css
  assets/html/themes/catppuccin-macchiato.css
  assets/html/themes/catppuccin-mocha.css
  assets/html/themes/documenter-dark.css
  assets/html/themes/documenter-light.css
  src/html/HTMLWriter.jl
Labels: Type: Enhancement, Format: HTML

#2680 remove spare parenthesis in examples.md
  docs/src/man/examples.md
Labels: Type: Documentation, Skip Changelog

#2685 Fix performance regression in `clear_modules!`
  CHANGELOG.md
  src/expander_pipeline.jl
Labels: Status: Backport Needed, Type: Bugfix
