Repository JuliaDocs/Documenter.jl, pull requests merged in 2025-06, with the labels that each got.

#2729 Pass GITHUB_TOKEN to link check if applicable
  .github/workflows/CI.yml
  CHANGELOG.md
  src/docchecks.jl
  test/online/online_linkcheck.jl
Labels: Type: Enhancement

#2697 Allow specifying a global default for `@meta` block settings
  CHANGELOG.md
  docs/src/man/syntax.md
  src/doctests.jl
  src/documents.jl
  src/expander_pipeline.jl
  src/makedocs.jl
  test/default_meta/src/index.md
  test/default_meta/tests.jl
  test/runtests.jl
Labels: Type: Enhancement

#2736 Change `rethrow(e)` to `rethrow()`
  src/deploydocs.jl
Labels: Type: Maintenance, Skip Changelog

#2742 Add command to run Runic into Makefile
  Makefile
  docs/src/contributing.md
Labels: Type: Maintenance, Skip Changelog

#2745 latest prettier version in CI
  .github/workflows/CI.yml
  assets/html/js/collapse.js
  assets/html/js/search.js
  assets/html/js/shortcut.js
  assets/html/js/versions.js
Labels: Skip Changelog
